### PR TITLE
Updated deprecated npm module

### PR DESCRIPTION
**Pull request by remojansen**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Updated deprecated npm module `dapr-client` --> `@dapr/dapr`

## Issue reference

n/a

### CODE REVIEW

**Review by mukundansundar — APPROVED** [review]
- [ ] @shubham1172 this is the new location for JS SDK right?
cc @XavierGeerinck

**Comment by shubham1172** [comment]
That is correct, @mukundansundar. Thanks for catching and updating @remojansen!

**Review by shubham1172 — APPROVED** [review]

**Review by shubham1172 — APPROVED** [review]

**Review by XavierGeerinck — APPROVED** [review]

**Review by mukundansundar — APPROVED** [review]

**Review by msfussell — APPROVED** [review]
LGTM

**Comment by msfussell** [comment]
@remojansen - Really appreciate your contribution here. Fixes like this are wonderful for the community.

**Pull request merged**
