### PR TITLE
Add a justification about the ratelimit middleware

### PR DESCRIPTION
**Pull request by RadoslavGatev**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Added a justification that compares the ratelimit middleware to the app-max-concurrency feature. That's a question that came up to me a few weeks ago and I had to examine the code in order to understand the difference between those two.

### CODE REVIEW

**Comment by msfussell** [comment]
Ideally this topic references the middleware ratelimit settings, which are currently missing from the docs and tracked in this issue https://github.com/dapr/docs/issues/840

**Comment by RadoslavGatev** [comment]
@msfussell, I can also add a page to document the ratelimit middleware this week. What do you think?

**Comment by yaron2** [comment]
> @msfussell, I can also add a page to document the ratelimit middleware this week. What do you think?

That would be awesome!

**Comment by AaronCrawfis** [comment]
> > @msfussell, I can also add a page to document the ratelimit middleware this week. What do you think?
> 
> That would be awesome!

Marking this PR as draft pending middleware ratelimiting. Thanks!

**Comment by RadoslavGatev** [comment]
@AaronCrawfis, I added a page for the rate limit middleware.

**Review by AaronCrawfis — APPROVED** [review]

**Pull request merged**
