### PR TITLE
update s3 bindings links

### PR DESCRIPTION
**Pull request by martbln**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Fixed the links to S3 bindings operations in the documentation.

### CODE REVIEW

**Comment by msfussell** [comment]
@martbln - Thanks for this PR. I suggest that we make this consistent, by renaming all the heading to files and referencing objects. So I suggest changing the following and also changing the headers to match.  Could you take a pass on the whole topic? Thanks

-  `create` : [Create object](#create-object)
- `get` : [Get object](#get-object)
- `delete` : [Delete object](#delete-object)
- `list`: [List objects](#list-objects)

**Comment by msfussell** [comment]
@martbln - Would love to get this change in tomorrow. Can you look at my feedback?

**Review by yaron2 — APPROVED** [review]

**Comment by msfussell** [comment]
@martbln - Pinging again?

**Comment by yaron2** [comment]
> @martbln - Pinging again?

Changes addressed. Thanks for your contribution @martbln

**Pull request merged**
