### PR TITLE
Update support-release-policy.md for 1.10.7

### PR DESCRIPTION
**Pull request by nyemade-uversky**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

### CODE REVIEW

**Review by msfussell — APPROVED** [review]
LGTM

**Review by msfussell — APPROVED** [review]
LGTM

**Review by msfussell — APPROVED** [review]
LGTM

**Review by msfussell — APPROVED** [review]
LGTM

**Comment by msfussell** [comment]
@nyemade-uversky  Looks like you need to pull the latest 1.10 changes for the build to pass.

**Comment by greenie-msft** [comment]
@nyemade-uversky @msfussell 

This file also needs updating: https://github.com/dapr/docs/blob/v1.10/daprdocs/layouts/shortcodes/dapr-latest-version.html

**Comment by nyemade-uversky** [comment]
@greenie-msft  PR updated. I've edited the dapr-latest-version.html file to update the old release version with the current 1.10.7 version.

**Pull request merged**
