### PR TITLE
Update diagram deck

### PR DESCRIPTION
**Pull request by hhunter-ms**
Update diagram deck with images added for 1.11

### CODE REVIEW

**Comment by msfussell** [comment]
Here are my suggestions
1) Can we update Icons slide to include workflow icon
2) remove slides 8-11. (Keeping on slide 12 in this set)
3) Remove 13 (keep 14)
4) Remove 22 and 23 (Keep 24)
5) Remove 40

Also this looks like it is not the latest deck. This image is missing https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-patterns/#fan-outfan-in

I have an image for Outbox pattern to add.

**Comment by hhunter-ms** [comment]
> Also this looks like it is not the latest deck. This image is missing https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-patterns/#fan-outfan-in

Fan out/fan in diagram isn't in the latest deck - just confirmed this after downloading the latest from the site. who created that slide? I don't have it.

> I have an image for Outbox pattern to add.

This PR is pointing to 1.11 - should the outbox pattern be added to a 1.12 PR?

**Comment by msfussell** [comment]
There is one crypto diagram now missing. This one https://v1-12.docs.dapr.io/developing-applications/building-blocks/cryptography/cryptography-overview/#cryptography-in-dapr

**Review by msfussell — APPROVED** [review]
LGTM

**Pull request merged**
