### PR TITLE
Docs for logging options in the Configuration spec

### LINKED ISSUE #2938: Docs for apiLogging options in Configuration CRD
The documentation for the Configuration CRD needs to be extended to include docs for `apiLogging`, as added in https://github.com/dapr/dapr/pull/5462

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
See dapr/dapr#5462

Fixes #2938

### CODE REVIEW

**Comment by msfussell** [comment]
This is a great update. The one other place is adding the K8s annotation for omitHealthChecks to the https://docs.dapr.io/reference/cli/dapr-annotate/ reference guide. Could you add this after the API logging annotation,

**Comment by ItalyPaleAle** [comment]
As discussed on discord, this change did not add new annotations so I don't think it needs to be on that page.

**Comment by hhunter-ms** [comment]
@ItalyPaleAle FYI, the broken link has been fixed in v1.10, but I can't seem to merge that update into your PR. Could you bring that in?

**Comment by ItalyPaleAle** [comment]
@hhunter-ms I can't either. Looks like the fix was in the 1.9 branch but not 1.10: https://github.com/dapr/docs/tree/v1.9

**Comment by hhunter-ms** [comment]
@ItalyPaleAle @msfussell weird - I would've thought the upmerge I did from v1.9 to v1.10 would bring it in. Rerunning to see if it fixes itself... 🤞

**Comment by hhunter-ms** [comment]
@ItalyPaleAle could you try pushing a small change?

**Comment by ItalyPaleAle** [comment]
@hhunter-ms i merged v1.10 into this branch, let's see if this works

**Review by msfussell — APPROVED** [review]
LGTM

**Pull request merged**
