### PR TITLE
Update setup-dynamodb.md

### PR DESCRIPTION
**Pull request by tuapuikia**
Update the Dynamodb states name to reflect the change in https://github.com/dapr/dapr/blob/master/cmd/daprd/main.go#L210

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

### CODE REVIEW

**Review by mukundansundar — CHANGES_REQUESTED** [review]
Please change line 10 too.

**Comment by AaronCrawfis** [comment]
> Please change line 10 too.

@tuapuikia

**Comment by orizohar** [comment]
@tuapuikia - can you please address the reviewers comments? Thanks!

**Comment by orizohar** [comment]
@mukundansundar - can you please suggest the change you'd like to see?

**Review by mukundansundar — APPROVED** [review]

**Review by orizohar — APPROVED** [review]

**Pull request merged**
