### PR TITLE
V1.2 python SDKDocs update - client

### LINKED ISSUE #1542: gRPC service extension examples won't run
**Describe the issue**
Dapr API in the Python SDK has changed, documentation examples do not run and gives errors

**URL of the docs**
This example fails: [https://docs.dapr.io/developing-applications/sdks/python/python-sdk-extensions/python-grpc/#listen-for-service-invocation-requests](https://docs.dapr.io/developing-applications/sdks/python/python-sdk-extensions/python-grpc/#listen-for-service-invocation-requests) 

**Expected content**
```
from dapr.ext.grpc import App, InvokeMethodRequest, InvokeMethodResponse

app = App()

@app.method(name='my-method')
def mymethod(request: InvokeServiceRequest) -> InvokeServiceResponse:
    print(request.metadata, flush=True)
    print(request.text(), flush=True)

    return InvokeServiceResponse(b'INVOKE_RECEIVED', "text/plain; charset=UTF-8")

app.run(50051)
```

**Screenshots**

**Additional context**
Seems to be correct in `master`: https://github.com/dapr/python-sdk/blob/master/examples/invoke-simple/invoke-receiver.py, so might be resolved when version is bumped

### LINKED ISSUE #1551: SDK examples links are broken and point to old code in other branches
**Describe the issue**
Manyh paths I try to find examples (namly Python paths, and general Dapr\Docs paths) lead to SDK content that is really old and incorrect, e.g. a setup branch from 2020.  The impact of this is the code is wrong, and it's not obvious why.  

**URL of the docs**
https://github.com/dapr/python-sdk/tree/daprdocs-setup/examples
https://github.com/dapr/docs/tree/v1.2/sdkdocs

**Expected content**
Point to the current SDK and examples in the main branches

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by paulyuk**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Updates Python SDK client documentation:
- fixes to match v1.2 Dapr release
- fixes links to point to main/1.2 branches
- adds Subscribe example

Note this is the matching PR to pair with python-SDK submodule PR:
https://github.com/dapr/python-sdk/pull/224 

## Issue reference

Fixes #1551

### CODE REVIEW

**Comment by paulyuk** [comment]
@wcs1only @berndverst advise and see if branching technique and separate PR is correct in this case.
https://github.com/dapr/python-sdk/pull/224

**Comment by paulyuk** [comment]
Let's hold for the pythonSDK change, and then I'll be about to use the upstream merged files

**Comment by paulyuk** [comment]
Let's wait on PR in Python SDKDocs to merge upstream, and I'll re-sync this change to submodule..

**Comment by paulyuk** [comment]
@AaronCrawfis could you please take a look?  This is simply a merge of Python SDK changes in sub module so we can release them to docs.dapr.io.  

Note this is the matching PR to pair with python-SDK submodule PR:
dapr/python-sdk#224

Fixes #1551

**Review by AaronCrawfis — APPROVED** [review]

**Pull request merged**
