### PR TITLE
Workflow backend documentation

### PR DESCRIPTION
**Pull request by ASHIQUEMD**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Workflow backend documentation

### CODE REVIEW

**Comment by hhunter-ms** [comment]
@ASHIQUEMD it looks like this PR is pulling in some old commits... could you remove the unrelated changes, esp the .github/workflows and config.toml docs?

**Comment by hhunter-ms** [comment]
@ASHIQUEMD now that I look at this again, should this be pointing to branch v1.13?

**Comment by msfussell** [comment]
@ASHIQUEMD - Please review and update

**Comment by ASHIQUEMD** [comment]
> @ASHIQUEMD - Please review and update

@msfussell I will be closing this PR because we haven't enabled sqlite backend, so we still have only actor backend and there is no change in the behavior of workflow backend. Once we enable other backends like sqlite, I will create a separate PR.

Please let me know your thoughts? I will close it accordingly.

**Pull request closed without merging**
