### PR TITLE
Modify path DaprRoot add the SystemDrive environment variable

### PR DESCRIPTION
**Pull request by hueifeng**
Signed-off-by: Huei Feng <695979933@qq.com>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

[cli/989](https://github.com/dapr/cli/pull/989)

### CODE REVIEW

**Review by mukundansundar — APPROVED** [review]
lgtm.
@greenie-msft @msfussell are there any other occurrences for `C:` in the docs?

**Review by mukundansundar — DISMISSED** [review]
@hueifeng Change the base branch to 1.9 and fix commits.

**Review by mukundansundar — APPROVED** [review]
@greenie-msft @nyemade-uversky @msfussell 
Can this be merged to 1.7 and also ported to 1.8 and 1.9?

**Comment by mukundansundar** [comment]
> @greenie-msft @nyemade-uversky @msfussell Can this be merged to 1.7 and also ported to 1.8 and 1.9?

Since the install script that docs uses are from master branch in CLI and 1.7 and 1.8 are also supported, this needs to added to those docs as well?

**Comment by greenie-msft** [comment]
> > @greenie-msft @nyemade-uversky @msfussell Can this be merged to 1.7 and also ported to 1.8 and 1.9?
> 
> Since the install script that docs uses are from master branch in CLI and 1.7 and 1.8 are also supported, this needs to added to those docs as well?

Yes, that is correct. Can you please create a PR for for 1.8 and we'll make sure it gets upmerged into 1.9

**Review by greenie-msft — APPROVED** [review]

**Comment by greenie-msft** [comment]
@mukundansundar nvm, i took care of the PR to 1.8

**Pull request merged**
