### PR TITLE
Update statemanagement-quickstart.md

### PR DESCRIPTION
**Pull request by louisquach**
Signed-off-by: Minh Luan Quach <61050316+louisquach@users.noreply.github.com>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

### CODE REVIEW

**Comment by msfussell** [comment]
@louisquach - Can you make these changes onto the v1.10 branch for the docs.

**Comment by louisquach** [comment]
@msfussell yes, sure!

**Comment by msfussell** [comment]
@louisquach - By simply switching the branch you bring in many other changes not related to this PR (there are 29 more files added). Either resolve these conflicts or open a new PR from a synced v1.10 branch. Thx

**Comment by louisquach** [comment]
@msfussell oh, sorry. I didn't mean to do that. I'll make a new PR.

**Comment by msfussell** [comment]
@louisquach - We need to close the docs for this release. Could you do the new PR soon? Thanks

**Comment by louisquach** [comment]
Hi @msfussell, I've made a new PR, sorry about that!

**Comment by hhunter-ms** [comment]
closing in favor of #3175

**Pull request closed without merging**
