### PR TITLE
modify unsubscribe config api respose

### PR DESCRIPTION
**Pull request by pravinpushkar**
Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>

## Issue reference
#2730

### CODE REVIEW

**Comment by pravinpushkar** [comment]
ping @msfussell @greenie-msft

**Review by greenie-msft — APPROVED** [review]

**Comment by hhunter-ms** [comment]
@pravinpushkar sorry this fell off the radar - is this still applicable for 1.9? if so, does it also apply to 1.10, 1.11, etc?

**Comment by msfussell** [comment]
@pravinpushkar If this is still relevant we should only apply this to v1.11 and then the update (v1) configuration apis. Can you PTAL and decide if the current docs still need updating?

**Comment by pravinpushkar** [comment]
@msfussell Seems these changes are already merged as part of some different PR. Only the example section is missing in current dapr docs. I will try to modify the PR. We can make it as part of 1.12 as it is only example that we will add.

**Comment by msfussell** [comment]
@pravinpushkar - So you updated this for v1.9. At this point it may not be worth updating v1.9. The question is whether any of this should apply to v1.11, which I presume not. In other words are the v1.11 reference docs for config currently correct?

**Comment by pravinpushkar** [comment]
> @pravinpushkar - So you updated this for v1.9. At this point it may not be worth updating v1.9. The question is whether any of this should apply to v1.11, which I presume not. In other words are the v1.11 reference docs for config currently correct?

@msfussell The current docs for v1.11 are correct and has up to date information. Lets keep this PR open till I make modification in this PR(only to add example section) and point it to v1.12 instead of earlier releases. 

Edit -  In fact, **lets close this**. I will open a different PR for creating an example.

**Review by msfussell — APPROVED** [review]
LGTM

**Pull request merged**
