### PR TITLE
Update resource name in pubsub to be valid

### PR DESCRIPTION
**Pull request by jjcollinge**
- add missing changes (#2239)
- Remove sentence about a pict since pict isn't there (#2242)
- update resource name to be valid

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description
Update the resource name used in the docs to be a valid resource name.

## Issue reference

Please reference the issue this PR will close: #2251

### CODE REVIEW

**Comment by msfussell** [comment]
@jjcollinge - Anything more to review here? Is this just changing app names?
 @hhunter-ms - Are you good with these changes?

**Comment by jjcollinge** [comment]
@msfussell I've not had time to validate the name change works in all the various places  it's used throughout this doc i.e .NET SDK, Powershell, curl, Dapr CLI etc. I've only tested that the declarative Subscription and Component resources now create in K8s without error. I can't think why this change would cause any issues in the other places but as I say I've not confirmed it doesn't.

**Comment by greenie-msft** [comment]
@jjcollinge is this still in the draft state, or are you ready for a review?

**Comment by jjcollinge** [comment]
@greenie-msft I will publish - is someone able to test the commands work in the various places the change is mentioned throughout the doc. I don't have pwsh, .net, java, etc. installed to test those bits.

**Review by greenie-msft — APPROVED** [review]

**Pull request merged**
