### PR TITLE
Remove WF from preview features list in support-preview-features.md

### PR DESCRIPTION
**Pull request by nyemade-uversky**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

### CODE REVIEW

**Comment by nyemade-uversky** [comment]
@hhunter-ms Found another wf update we'll need for 1.12 beta

**Comment by hhunter-ms** [comment]
related issue: #3567

**Comment by hhunter-ms** [comment]
just realized this was a PR, not an issue lol

**Comment by hhunter-ms** [comment]
@nyemade-uversky this PR should be pointing to v1.12 branch, right?

**Comment by msfussell** [comment]
@hhunter-ms See this comment https://github.com/dapr/docs/issues/3567#issuecomment-1732066766
There are other changes needed to preview (multia-app), so maybe close this PR and open a new one.

**Pull request closed without merging**
