### PR TITLE
Document the new fields in Configuration's tracing section.

### PR DESCRIPTION
**Pull request by tcnghia**
## Description

Document the new fields in Configuration's tracing section. This is a follow up of https://github.com/dapr/dapr/pull/2532 .

## Issue reference

Fixes https://github.com/dapr/docs/issues/978

### CODE REVIEW

**Comment by tcnghia** [comment]
@orizohar @msfussell can you please help take a look at this small PR? thanks!

**Comment by msfussell** [comment]
One thing that it would be good to add as part of this PR is to be clear that metrics can also be included as its own section. It is explicitly being missed here. It is in this doc https://v1-rc1.docs.dapr.io/developing-applications/building-blocks/observability/metrics/ but it would be good to have this all in one place.

So can you add metrics?
Otherwise this looks good.

Like this
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "1"
  metric:
    enabled: false

**Comment by tcnghia** [comment]
> One thing that it would be good to add as part of this PR is to be clear that metrics can also be included as its own section. It is explicitly being missed here. It is in this doc https://v1-rc1.docs.dapr.io/developing-applications/building-blocks/observability/metrics/ but it would be good to have this all in one place.
> 
> So can you add metrics?
> Otherwise this looks good.
> 
> Like this
> apiVersion: dapr.io/v1alpha1
> kind: Configuration
> metadata:
> name: tracing
> namespace: default
> spec:
> tracing:
> samplingRate: "1"
> metric:
> enabled: false

Done now

**Review by msfussell — APPROVED** [review]
LGTM

**Pull request merged**
