### PR TITLE
Update setup-azure-servicebus.md

### PR DESCRIPTION
**Pull request by jjcollinge**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Update docs in accordance with the following PR: https://github.com/dapr/components-contrib/pull/713/files

## Issue reference

<!--Please reference the issue this PR will close: #1275

### CODE REVIEW

**Comment by mukundansundar** [comment]
@jjcollinge can you add v1.1 docs since this feature will only be in the next release?

**Comment by jjcollinge** [comment]
@mukundansundar yep sorry meant to do this after publish - thanks.

**Comment by mukundansundar** [comment]
@jjcollinge Can you check what these additional commits are? Except for the new fields that were added, do the other changes need to be put in 1.0 as well or is it already fixed and being ported from 1.0 into 1.1? @orizohar

**Comment by orizohar** [comment]
> @jjcollinge Can you check what these additional commits are? Except for the new fields that were added, do the other changes need to be put in 1.0 as well or is it already fixed and being ported from 1.0 into 1.1? @orizohar

@mukundansundar - other files were picked up from v1.0 and now after #1287 are no longer part of this PR

**Review by mukundansundar — APPROVED** [review]
can be merged after https://github.com/dapr/components-contrib/pull/713/files is merged

**Review by AaronCrawfis — APPROVED** [review]

**Comment by mukundansundar** [comment]
The PR https://github.com/dapr/components-contrib/pull/713/files is merged to components contrib, will later be picked up in dapr/dapr (as part of release or a PR before that) so this PR can be merged for v1.1 docs.

**Pull request merged**
