### PR TITLE
doc: Update PubSub - Azure Event Hub for clarity

### PR DESCRIPTION
**Pull request by XavierGeerinck**
Added the following changes to make it more easy to utilize the docs for PubSub - Azure Event Hub
* Make the example easily copy-pastable (now it's not working when copy pasted due to several lines causing Dapr to fail on start-up with `error initializing pub sub pubsub.azure.eventhubs/v1: json: invalid use of ,string struct tag, trying to unmarshal "" into int32`)

Signed-off-by: Xavier Geerinck <xavier.geerinck@gmail.com>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

### CODE REVIEW

**Comment by greenie-msft** [comment]
@XavierGeerinck thank you for fixing the examples. We strive to have our component specs list all the possible fields and metadata at the start of the doc. After that, having the getting started guide with the examples you've provided would be great to have. 

Can you please re-order the current PR to reflect this order? 

PR looks great otherwise. Thank you for the contribution!

**Comment by greenie-msft** [comment]
@XavierGeerinck also just noticed, can you please update the branch to v1.8?

**Comment by XavierGeerinck** [comment]
@greenie-msft added them to the top

**Comment by XavierGeerinck** [comment]
Branch was outdated and diverged too much so had to open a new PR under #2772 since DCO didn't want to pass, apologies

**Pull request closed without merging**
