### PR TITLE
Fix/issue 2277

### LINKED ISSUE #2277: Quickstart: Publish and Subscribe error in starting .NET checkout command
**URL of the docs page**
https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/

**How is it currently worded?**
`dapr run --app-id checkout --components-path ../../components -- dotnet run`

**How should it be worded?**
`dapr run --app-id checkout --components-path ../../../components -- dotnet run`

**Additional context**
Currently, running the command results in the error `CreateFile ../../components: The system cannot find the file specified.`

### PR DESCRIPTION
**Pull request by vidarkongsli**
Signed-off-by: Vidar Kongsli <vidar@kongs.li>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Fix example command to start checkout  and order processor for .NET in pub sub quicksetart

## Issue reference

Closes #2277

### CODE REVIEW

**Comment by yaron2** [comment]
@vidarkongsli please resolve the conflicts. thanks!

**Comment by vidarkongsli** [comment]
> @vidarkongsli please resolve the conflicts. thanks!

Done.

**Comment by greenie-msft** [comment]
Hi @vidarkongsli, thank you for your contribution, but it looks like your suggested changes were already addressed by a separate PR. After fixing the conflicts, it appears this PR does not seem to change anything. I'm going to close this for now, but feel free to reopen if I'm mistaken. 

Thank you.

**Comment by msfussell** [comment]
@vidarkongsli - Unless I am missing something, this PR does not fix anything (the diffs are the same) so closing this PR. Thanks for taking a look

**Pull request closed without merging**
