### PR TITLE
Jocko wowza patch 1

### PR DESCRIPTION
**Pull request by jocko-wowza**
# Description

Fixed bad JSON in the CURL example on the Output Bindings How-To

## Issue reference

No issue to reference, found it on my own.

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [N/A] Code compiles correctly
* [N/A] Created/updated tests
* [x] Extended the documentation

### CODE REVIEW

**Comment by yaron2** [comment]
Thanks for this, good catch!

Please sign the CLA so we can merge this.

**Comment by yaron2** [comment]
This PR includes changes from https://github.com/dapr/docs/pull/237. Can you remove them? (The Event triggering section)

**Comment by jocko-wowza** [comment]
I'll redo the PR.

**Comment by yaron2** [comment]
ok

**Pull request closed without merging**
