### PR TITLE
Kafka SASL SCRAM Authentication

### PR DESCRIPTION
**Pull request by mindovermiles262**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Adds Documentation for MSK Authentication using SASL SCRAM-256 and 512

## Issue reference

Previous PR: https://github.com/dapr/docs/pull/2621

Issue: https://github.com/dapr/components-contrib/issues/1109

### CODE REVIEW

**Comment by mukundansundar** [comment]
@dapr/maintainers-docs This change is needed in 1.9 docs.... its a new property that was introduced in 1.9. 
cc @dapr/maintainers-components-contrib

**Review by yaron2 — APPROVED** [review]

**Comment by mukundansundar** [comment]
@yaron2 modified milestone since this feature was released with 1.9

**Comment by yaron2** [comment]
But the PR was technically done as part of the 1.10 milestone, and the contribution deserves attribution.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-sasl/info/issues/1
- https://github.com/dapr/docs/pull/2621
- https://github.com/dapr/docs/pull/2624
- https://github.com/dapr/docs/pull/2637
- https://github.com/dapr/docs/pull/2939
- https://github.com/dapr/components-contrib/issues/1109
- https://github.com/dapr/components-contrib/pull/1856

**Pull request merged**
