### PR TITLE
Cleaned up binding quickstart text

### PR DESCRIPTION
**Pull request by bibryam**
Signed-off-by: Bilgin Ibryam <bibryam@gmail.com>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [+] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [+] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [+] Commands include options for Linux, MacOS, and Windows within codetabs
- [+] New file and folder names are globally unique
- [+] Page references use shortcodes instead of markdown or URL links
- [+] Images use HTML style and have alternative text
- [+] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description
- Updated the output shown from the database query
- Fixed cron endpoint name to match what is in the code
- Fixed Java example descriptions

### CODE REVIEW

**Review by hhunter-ms — APPROVED** [review]
lgtm - thanks! @bibryam pulling latest from v1.8 should fix the link validation error

**Comment by hhunter-ms** [comment]
@bibryam could you point this PR to v1.8 instead of v1.9?

**Comment by bibryam** [comment]
Sure. Was I supposed to do it for 1.8 or always pick the latest version?

**Comment by hhunter-ms** [comment]
> Sure. Was I supposed to do it for 1.8 or always pick the latest version?

Until the 1.9 release, we target most non-milestone updates to 1.8 (or whatever the current version is). We'll push 1.8 into 1.9 at release.

**Comment by bibryam** [comment]
Sorry for the mess, I'll close this and make a new PR with the right base version.

**Pull request closed without merging**
