### PR TITLE
Update setup-jetstream.md

### PR DESCRIPTION
**Pull request by siredmar**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Added missing information how to create the JetStream. Creating a JetStream is essential. Otherwise the pub/sub for jetstream won't work properly.

## Issue reference

#2001

### CODE REVIEW

**Comment by siredmar** [comment]
@yaron2 would you please review this PR?

**Review by msfussell — APPROVED** [review]
LGTM

**Comment by msfussell** [comment]
@siredmar - Can you resubmitted this PR with a DCO signature, which is required. See https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work Thanks

**Comment by siredmar** [comment]
@msfussell ok now?

**Review by msfussell — APPROVED** [review]
LGTM

**Pull request merged**
