### PR TITLE
Adds settings for SASL SCRAM SHA-256 and SHA-512

### PR DESCRIPTION
**Pull request by mindovermiles262**
Signed-off-by: Andrew <mindovermiles262@gmail.com>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Adds Documentation on how to use SASL SCRAM SHA-256 and SHA-512 Authentication

## Issue reference

https://github.com/dapr/components-contrib/issues/1109)](https://github.com/dapr/components-contrib/issues/1109

### CODE REVIEW

**Review by msfussell — APPROVED** [review]
Thanks for this contribution. Appreciate this.

**Comment by yaron2** [comment]
Need to revert this PR, this functionality is slated for 1.9.

**Comment by yaron2** [comment]
@mindovermiles262 please open the PR again against the v1.9 branch once it's ready (will likely be created tomorrow).

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-sasl/info/issues/1

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-sasl/info/issues/1
- https://github.com/dapr/docs/pull/2621
- https://github.com/dapr/docs/pull/2624
- https://github.com/dapr/docs/pull/2637
- https://github.com/dapr/docs/pull/2939
- https://github.com/dapr/components-contrib/issues/1109
- https://github.com/dapr/components-contrib/pull/1856

**Pull request merged**
