### PR TITLE
Azure Key Vault RBAC role to get secrets updated

### PR DESCRIPTION
**Pull request by SergioVelmay**
## Description

I found an error or typo on [this documentation page](https://docs.dapr.io/reference/components-reference/supported-secret-stores/azure-keyvault/#steps).  
In step 5 it says:
> Using RBAC, assign a role to the Azure AD application so it can access the Key Vault.  
In this case, assign the “Key Vault Crypto Officer” role, which has broad access; other more restrictive roles can be used as well, depending on your application.  

The 'Key Vault Crypto Officer' role only has the 'Read Secret Properties' permission over Azure Key Vault, which means 'View the properties of a secret, but not its value'.  
I think it would be better to use, for example, the 'Key Vault Secrets User' role which does have the 'Get secrets' permission over Azure Key Vault and can 'Gets the value of a secret'.  
According to [Microsoft's documentation](https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-guide?tabs=azure-cli#azure-built-in-roles-for-key-vault-data-plane-operations), the 'Key Vault Secrets Officer' role and the 'Key Vault Administrator' role would also work.  

The changes added to this Pull Request were discussed in [this Discord thread](https://discord.com/channels/778680217417809931/901141875585609869/948190811533742090).  

Signed-off-by: Sergio Velmay <sergiovelmay@gmail.com>

### CODE REVIEW

**Comment by msfussell** [comment]
@SergioVelmay Thanks for this contribution. Just to be clear using the Cryto role does not cause this to fail, correct? Just trying to be clearer on the guidance on when to use which role, especially in the updated paragraph that you added. When would you choose to use the Crypto RBAC role then?

Also as FYI please take a look at this now merged PR, since would like to get any input from you on these update https://github.com/dapr/docs/pull/2241#pullrequestreview-909458644

**Comment by SergioVelmay** [comment]
Hi @msfussell it is an honor for me. @yaron2 encouraged me to contribute on this topic.

The  'Key Vault Crypto Officer' role (like the 'Key Vault Crypto Service Encryption User' and the 'Key Vault Crypto User') is allowed to perform some actions on the keys but not on the values of the secrets stored in the Azure Key Vault resource. If you use any of these 'Crypto' roles to read or get secret values from your application, you will receive a 'forbidden' or 'unauthorized' error.

I realized this when I implemented the Key Vault secret store in my tests with the [DaprTrafficControl](https://github.com/EdwinVW/dapr-traffic-control) and the [eShopOnDapr](https://github.com/dotnet-architecture/eShopOnDapr) projects.

Next weekend, I will try to take a look at the issue you mentioned before (https://github.com/dapr/docs/pull/2241#pullrequestreview-909458644).

**Review by greenie-msft — APPROVED** [review]

**Comment by SergioVelmay** [comment]
@msfussell I have more information about the permissions of all these RBAC roles over Azure Key Vault resources. You can run the same commands with Azure CLI to see the available actions over keys ('Microsoft.KeyVault/vaults/keys/') and values ('Microsoft.KeyVault/vaults/secrets/') of the Key Vault secrets.
- Roles without 'getSecrets' permission that cannot read secret values.
  - Key Vault Crypto User
    `az role definition list --name "Key Vault Crypto User" --output json --query '[].permissions[0].dataActions'`
    ```
      "Microsoft.KeyVault/vaults/keys/read",
      "Microsoft.KeyVault/vaults/keys/update/action",
      "Microsoft.KeyVault/vaults/keys/backup/action",
      "Microsoft.KeyVault/vaults/keys/encrypt/action",
      "Microsoft.KeyVault/vaults/keys/decrypt/action",
      "Microsoft.KeyVault/vaults/keys/wrap/action",
      "Microsoft.KeyVault/vaults/keys/unwrap/action",
      "Microsoft.KeyVault/vaults/keys/sign/action",
      "Microsoft.KeyVault/vaults/keys/verify/action"
  - Key Vault Crypto Officer
    `az role definition list --name "Key Vault Crypto Officer" --output json --query '[].permissions[0].dataActions'`
    ```
      "Microsoft.KeyVault/vaults/keys/*",
      "Microsoft.KeyVault/vaults/keyrotationpolicies/*"
  - Key Vault Crypto Service Encryption User
    `az role definition list --name "Key Vault Crypto Service Encryption User" --output json --query '[].permissions[0].dataActions'`
    ```
      "Microsoft.KeyVault/vaults/keys/read",
      "Microsoft.KeyVault/vaults/keys/wrap/action",
      "Microsoft.KeyVault/vaults/keys/unwrap/action"
- Roles with 'getSecrets' permission that can read secret values.
  - Key Vault Secrets User
    `az role definition list --name "Key Vault User" --output json --query '[].permissions[0].dataActions'`
    ```
      "Microsoft.KeyVault/vaults/secrets/getSecret/action",
      "Microsoft.KeyVault/vaults/secrets/readMetadata/action"
  - Key Vault Secrets Officer
    `az role definition list --name "Key Vault Secrets Officer" --output json --query '[].permissions[0].dataActions'`
    ```
      "Microsoft.KeyVault/vaults/secrets/*"
  - Key Vault Administrator
    `az role definition list --name "Key Vault Administrator" --output json --query '[].permissions[0].dataActions'`
    ```
      "Microsoft.KeyVault/vaults/*"
I hope this information is useful to you.

**Review by msfussell — APPROVED** [review]
LGTM

**Pull request merged**
