### PR TITLE
Replace button by alert section since there is some issue about crowdin

### PR DESCRIPTION
**Pull request by newbe36524**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

These special a tags are not properly recognized in crowdin.com (the translation management tool we are using). I have tried very many other approaches that do not work properly. So, I modified these a tags to alert tags. This retains the eye-catching effect and solves the recognition problem.

### CODE REVIEW

**Comment by newbe36524** [comment]
Hi, @AaronCrawfis  it seems that there is a issue about github action. 
I found this problem with all the requests submitted recently. Can you please help me look at it?

**Comment by AaronCrawfis** [comment]
> Hi, @AaronCrawfis it seems that there is a issue about github action.
> I found this problem with all the requests submitted recently. Can you please help me look at it?

#1378 will address this issue. For PRs from forked repos the deploy token isn't available, so we want to build but not deploy to the staging site.

**Comment by AaronCrawfis** [comment]
@newbe36524 thanks for noticing the broken crowdin support! Instead of an alert shortcode, I made a new button shortcode that should meet both our requirements: https://docs.dapr.io/contributing/contributing-docs/#buttons

Please let me know if you have any issues

**Review by AaronCrawfis — CHANGES_REQUESTED** [review]
Please use the new button shortcode: https://docs.dapr.io/contributing/contributing-docs/#buttons

**Review by AaronCrawfis — APPROVED** [review]

**Pull request merged**
