### PR TITLE
Add TypeScript howto

### PR DESCRIPTION
**Pull request by subesokun**
# Description

Add TypeScript howto

## Issue reference

closes https://github.com/dapr/samples/issues/157

### CODE REVIEW

**Comment by youngbupark** [comment]
LGTM. Thanks! @subesokun 

@msfussell @orizohar @yaron2 Please review this doc.

**Comment by youngbupark** [comment]
@orizohar Can you please review this pr ?

**Comment by orizohar** [comment]
Looking at this PR, it seems like viewers who want to run this demo need to clone the repo an run it? if so, the docs repo may not be the best place for this.

@msfussell @amanbha - I'd like your take on this

**Comment by orizohar** [comment]
> Looking at this PR, it seems like viewers who want to run this demo need to clone the repo an run it? if so, the docs repo may not be the best place for this.
> 
> @msfussell @amanbha - I'd like your take on this

Apologies, I now see in the issue that @msfussell asked for this in the doc. I'll let him review this.

**Comment by subesokun** [comment]
> Looking at this PR, it seems like viewers who want to run this demo need to clone the repo an run it? if so, the docs repo may not be the best place for this.
> 
> @msfussell @amanbha - I'd like your take on this

Yes, you need to clone the code as it's a bit more than just a hello world example so I'm not sure too if it's really a good fit for the howto docs or if it's more like an example app. It's somehow a bit of both, an example app and a how-to. If you render a document out of this repo then it's most probably the wrong place as you can't look up easily the related source code.

Initially, I wrote a step-by-step manual for setting up the TS config, adding the linter, adding Dapr, and so on but most of the steps were not Dapr related (just setting up a basic TS project, and those steps are frequently changing). So I thought it would be maybe more helpful to provide a ready-to-use app as a reference with some additional information.

I'll have a look again and check if I can split up the PR into a minimal how-to and then move the example app source code e.g. into the [js-sdk](https://github.com/dapr/js-sdk) or [samples](https://github.com/dapr/samples) repo + leave a link in the how-to.

**Comment by artursouza** [comment]
@orizohar Any updates on this?

**Comment by subesokun** [comment]
Sorry, I didn't have yet the time to continue working on this PR and I think I need to update the docu too as it's most likely already out-of-date. Once I'll find time then I continue working on a new PR but for now, I'd like to close this one.

**Pull request closed without merging**
