### PR TITLE
Update install-dapr-cli.md

### PR DESCRIPTION
**Pull request by victorp13**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [V] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [V] Commands include options for Linux, MacOS, and Windows within codetabs
- [V] New file and folder names are globally unique
- [V] Page references use shortcodes instead of markdown or URL links
- [V] Images use HTML style and have alternative text
- [V] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Updated "Verify installation" response to the "dapr" command, to reflect latest version's response. 🤓

## Issue reference

None

### CODE REVIEW

**Review by mukundansundar — COMMENTED** [review]
@victorp13 Please add a signoff to satisfy the DCO check. 
https://probot.github.io/apps/dco/

**Comment by victorp13** [comment]
@mukundansundar Installed the DCO to all my repos. Am I doing the below right? Not comfortable sharing email address.

Signed-off-by: Victor Pikula <victorp13>

**Comment by yaron2** [comment]
> @mukundansundar Installed the DCO to all my repos. Am I doing the below right? Not comfortable sharing email address.
> 
> Signed-off-by: Victor Pikula

You do not need to install DCO to your repos, just to sign off your commits. See here: https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md#how-to-add-sign-offs-retroactively

**Review by greenie-msft — APPROVED** [review]

**Comment by greenie-msft** [comment]
@victorp13  The build will not pass until you have signed-off on your commits (DOC check). Instructions can be found here: https://github.com/dapr/docs/pull/2036/checks?check_run_id=4477577855

Thank you

**Pull request closed without merging**
