### PR TITLE
Update info about supported Kubernetes versions

### PR DESCRIPTION
**Pull request by dmitsh**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Update info about supported Kubernetes versions

## Issue reference

https://github.com/dapr/dapr/issues/3348

### CODE REVIEW

**Review by AaronCrawfis — APPROVED** [review]
From a docs style perspective it looks good, but want @msfussell to take a look as well.

**Comment by dmitsh** [comment]
@AaronCrawfis @msfussell , could you tag this PR to v1.3?

**Comment by artursouza** [comment]
I am concerned about dropping support to 1.17 at this point.

**Review by artursouza — CHANGES_REQUESTED** [review]
We need to make this decision as maintainers first.

**Comment by AaronCrawfis** [comment]
Good to merge on Thursday

**Comment by AaronCrawfis** [comment]
Please add the link to Kubernetes Skew versions to https://docs.dapr.io/operations/support/support-release-policy/#upgrade-on-hosting-platforms in addition to the overview. (add it as a ### heading under upgrade on hosting platforms)

**Review by AaronCrawfis — APPROVED** [review]

**Pull request merged**
