### PR TITLE
1440 secret key ref explanation

### PR DESCRIPTION
**Pull request by georgestevens99**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

I changed the text of the doc to reflect the areas that were missing as stated in Issue 1440.

## Issue reference

 
#1440

### CODE REVIEW

**Comment by msfussell** [comment]
This is a great clarification on the use of secrets, and those where the "key" is part of the actual secret itself like connection strings. My main feedback is that rather than calling these "Standard Case" and "Special Case", using descriptive names would be better, something like "embedded key" case and "string only " case.

**Comment by georgestevens99** [comment]
I am ready to apply Marks feedback on renaming some things.  But I am unsure how to proceed?  Which repo should I fork?  Is this like starting anew, or should I start from the changes in progress and now to do that?  Thanks.

**Comment by greenie-msft** [comment]
@georgestevens99 Can you please address @msfussell's comment so we can merge this? Thank you.

**Comment by georgestevens99** [comment]
I addressed Marks comment yesterday, in this branch. "It says Merging is blocked
Merging can be performed automatically with 1 approving review."

It seems someone needs to review the changes I made yesterday.  Is there anything I can do on my end?

**Review by msfussell — APPROVED** [review]
These changes are great!

**Review by orizohar — APPROVED** [review]

**Pull request merged**
