### PR TITLE
How to contribute with a new feature

### PR DESCRIPTION
**Pull request by artursouza**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

How to contribute with a new feature

## Issue reference

N/A

### CODE REVIEW

**Comment by msfussell** [comment]
This a a good start, however needs to be aligned with the existing overview https://docs.dapr.io/contributing/contributing-overview/ and link into contributing to docs https://docs.dapr.io/contributing/contributing-docs/ and SDKs topics. Are you tying to rewrite the overview?

**Comment by artursouza** [comment]
> This a a good start, however needs to be aligned with the existing overview https://docs.dapr.io/contributing/contributing-overview/ and link into contributing to docs https://docs.dapr.io/contributing/contributing-docs/ and SDKs topics. Are you tying to rewrite the overview?

I looked at the other docs too, they are specific about how to make contributions but not about how to deliver a feature. This document is a new dimension, giving a process overview for new features. I can link to those but making a contribution to Dapr does not necessarily explain how to deliver a feature. Delivering a feature requires many contributions.

**Comment by orizohar** [comment]
Is there a reason why this is going to v1.6? looks like this is not dependent on a specific runtime version and can go into v1.5

**Comment by AaronCrawfis** [comment]
@artursouza  please advise on 1.6 vs. 1.5

**Pull request closed without merging**
