### PR TITLE
Removed upgrade page as it's covered within the production guidelines doc

### PR DESCRIPTION
**Pull request by AaronCrawfis**
Covered elsewhere and duplicate

### CODE REVIEW

**Comment by orizohar** [comment]
@yaron2 - can you quickly confirm we are not losing any info here?

**Comment by AaronCrawfis** [comment]
Other docs are here: https://v1-rc2.docs.dapr.io/operations/hosting/kubernetes/kubernetes-upgrade/

**Comment by yaron2** [comment]
Please wait for my review

**Comment by AaronCrawfis** [comment]
@yaron2 with the CLI now supporting `dapr upgrade` should we keep this page in rc3 and delete it from 0.11?

**Comment by orizohar** [comment]
@yaron2 , can you take a look at this? looks like it's waiting for your review

**Comment by AaronCrawfis** [comment]
Duplicated page is here: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production/#upgrading-dapr-with-helm

**Pull request closed without merging**
