### PR TITLE
update pub/sub aws snssqs component to 'beta'

### PR DESCRIPTION
**Pull request by amimimor**
Signed-off-by: Amit Mor <amit.mor@hotmail.com>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

update pub/sub aws snssqs component to 'beta'

### CODE REVIEW

**Comment by msfussell** [comment]
@amimimor - Is this moving to Beta based on added conformance test cases or something else?

**Comment by amimimor** [comment]
> @amimimor - Is this moving to Beta based on added conformance test cases or something else?
> 
> 

Yes. Conformance tests had been added, PR'd and merged and this is per the maintainers request

**Comment by msfussell** [comment]
@amimimor  - Is there a PR/Issue for the conformance test that you could link this issue to? Thanks

**Comment by amimimor** [comment]
> @amimimor  - Is there a PR/Issue for the conformance test that you could link this issue to? Thanks

https://github.com/dapr/components-contrib/pull/1394

**Review by msfussell — APPROVED** [review]
Adding the link to conformance tests as per point 3 here https://docs.dapr.io/operations/components/certification-lifecycle/#beta

**Pull request merged**
