### PR TITLE
Update newly stable components in 1.11

### PR DESCRIPTION
**Pull request by berndverst**
This updates the components now considered stable in 1.11.

### CODE REVIEW

**Review by greenie-msft — APPROVED** [review]

**Review by greenie-msft — APPROVED** [review]

**Comment by berndverst** [comment]
FYI - building this with hugo locally fails, but it has nothing to do with my PR

```
Start building sites …
hugo v0.111.3+extended darwin/arm64 BuildDate=unknown
WARN 2023/05/03 15:33:27 .Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct similar to the one below:

  {{ $path := "" }}
  {{ with .File }}
	{{ $path = .Path }}
  {{ else }}
	{{ $path = .Path }}
  {{ end }}


Re-run Hugo with the flag --panicOnWarning to get a better error message.
ERROR 2023/05/03 15:33:30 [en] REF_NOT_FOUND: Ref "pluggable-components-go": "/Users/bverst/src/dapr/docs/daprdocs/content/en/developing-applications/develop-components/pluggable-components/pluggable-components-sdks/_index.md:17:8": page not found
ERROR 2023/05/03 15:33:30 [en] REF_NOT_FOUND: Ref "pluggable-components-dotnet": "/Users/bverst/src/dapr/docs/daprdocs/content/en/developing-applications/develop-components/pluggable-components/pluggable-components-sdks/_index.md:18:10": page not found
Error: Error building site: logged 2 error(s)
Total in 6939 ms
```

**Comment by msfussell** [comment]
@berndverst  -  To resolve the local Hugo Issue run
`git submodule update --init --recursive`
and to resolve the Azure static webapp issue pull the latest from the v1.11 docs branch.

**Review by msfussell — APPROVED** [review]

**Comment by msfussell** [comment]
Many of these overlap with earlier PRs from Roberto, so you will have to pull those changes first.

**Comment by hhunter-ms** [comment]
@berndverst can you pull in the build fixes from v1.11?

**Pull request merged**
