### PR TITLE
[AWS SSM parameter store] Add prefix option

### PR DESCRIPTION
**Pull request by hhunter-ms**
#2763

### CODE REVIEW

**Comment by msfussell** [comment]
@berndverst - Can you check this PR for correctness also?

**Review by msfussell — APPROVED** [review]
LGTM

**Comment by hhunter-ms** [comment]
@ostreek could you review as well?

**Comment by ostreek** [comment]
Sorry for the slow reply Hannah, I didn't get a notification. Thanks for picking this up. What you've written is correct, I agree with this change.

The docs for the Azure key vault secret store are very good, they give an example of how to create a key vault and configure the component to use it. It'd be great if we could provide similar instructions here, to show how to use the prefix option and explain how it maps to the parameter store. But I suggest you merge this PR now and maybe we can further improve the page later.

Thanks again for documenting this, I'm sorry I didn't do this at the time!

**Pull request merged**
