### PR TITLE
Updated azure app config metadata fields name

### PR DESCRIPTION
**Pull request by pravinpushkar**
Thank you for helping make the Dapr documentation better!

## Description

Updated metadata fields name in this PR.

## Issue reference

There is no separate issue . Changes are done along with a separate feature impln.
PR - https://github.com/dapr/components-contrib/pull/2088

### CODE REVIEW

**Comment by msfussell** [comment]
@pravinpushkar - Looks good, on the updates. You also need to update the Components table here https://v1-9.docs.dapr.io/reference/components-reference/supported-configuration-stores/ so this appears into the list of supported configuration stores. If currently does not show on the page, (only under the index)

**Comment by msfussell** [comment]
@pravinpushkar - Also please review this PR https://github.com/dapr/docs/pull/2810

**Comment by pravinpushkar** [comment]
> @pravinpushkar - Looks good, on the updates. You also need to update the Components table here https://v1-9.docs.dapr.io/reference/components-reference/supported-configuration-stores/ so this appears into the list of supported configuration stores. If currently does not show on the page, (only under the index)

Updated.

**Review by msfussell — APPROVED** [review]
LGTM

**Pull request merged**
