### PR TITLE
Correct OTel endpointAddress argument (it's not a URL)

### PR DESCRIPTION
**Pull request by andrejpk**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

The Tracing docs imply that you should use a URL in tracing.otel.endpointAddress but it's looking for a hostname or hostname:port

## Issue reference

#4068

### CODE REVIEW

**Comment by msfussell** [comment]
@andrejpk - Love this contribution. Any chance you could target this at the v1.13 branch now. This came at a time when we were close to the v1.13 release which is now the current branch

**Comment by hhunter-ms** [comment]
hey @andrejpk - second Mark's comment; hopefully that'll get rid of all the extra commits in this PR.

**Comment by hhunter-ms** [comment]
Resurrecting this PR - @andrejpk could you reopen this PR and point it to 1.13 instead of 1.12?

**Comment by andrejpk** [comment]
Replaced with #4145

**Pull request closed without merging**
