### PR TITLE
Add support for CockroachDB StateStore

### PR DESCRIPTION
**Pull request by r-c-correa**
## Description
Add Query support for  CockroachDB StateStore

## Issue reference
#2236

### CODE REVIEW

**Comment by msfussell** [comment]
@r-c-correa - Not sure where my last comments went, however can you remove the sections on Actor usage, since this is general to all transactional state stores and covered in the overview table. I would love to get this merged in ASAP! Thanks

**Comment by r-c-correa** [comment]
@msfussell I sent a commit with your considerations. If you want that I change something let me know. 😄

**Comment by yaron2** [comment]
@msfussell this is now merged in Dapr: https://github.com/dapr/dapr/pull/4335. Please re-review :)

**Review by msfussell — APPROVED** [review]
LGTM

**Pull request merged**
