### PR TITLE
Update sendgrid documentation

### PR DESCRIPTION
**Pull request by arahja**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [X] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [X] Commands include options for Linux, MacOS, and Windows within codetabs
- [X] New file and folder names are globally unique
- [X] Page references use shortcodes instead of markdown or URL links
- [X] Images use HTML style and have alternative text
- [X] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Updated the sendgrid module documentation to represent the [PR](https://github.com/dapr/components-contrib/issues/1749) marked for v1.8 release.

## Issue reference
#2452

### CODE REVIEW

**Comment by msfussell** [comment]
@arahja - Can you removed all the other files not need in this PR. Only sendgrid. You will need to rebase your branch.

**Comment by msfussell** [comment]
@arahja - Pinging again. See comment above ^^^

**Comment by yaron2** [comment]
@arahja please open a new PR with the relevant changes.

**Comment by arahja** [comment]
I created a new PR #2503
Sorry, I made the change against the wrong version branch.

**Comment by msfussell** [comment]
Closing this PR which is replaced by https://github.com/dapr/docs/pull/2503

**Pull request closed without merging**
