### PR TITLE
bindings: support rabbitmq send any content types

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long <long.dai@intel.com>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Support rabbitmq binding send any content types.

## Issue reference

https://github.com/dapr/components-contrib/pull/1147

### CODE REVIEW

**Comment by msfussell** [comment]
Please take a look at my changes

**Comment by daixiang0** [comment]
Oh, I miss it, thanks @msfussell

**Comment by daixiang0** [comment]
@msfussell could we merge it?

**Comment by orizohar** [comment]
@daixiang0 - can you change the target branch of the PR to be v1.5 (currently is v1.4)?

**Comment by daixiang0** [comment]
@orizohar done.

**Comment by msfussell** [comment]
@daixiang0 -  Looks like my changes were not applied. The new content type field should also be include in the example YAML file. Like this
  - name: maxPriority
    value: 5
- name: contentType
    value: "text/plain"

**Comment by orizohar** [comment]
> @orizohar done.

@daixiang0 - this PR is still trying to merge into v1.4. It should be changed to merge into v1.5

**Comment by daixiang0** [comment]
@orizohar I have changed the base to v1.5, please check again, thanks.

**Comment by greenie-msft** [comment]
@msfussell I do see your changes applied in the example yaml. Going to approve this PR.

**Review by greenie-msft — APPROVED** [review]

**Pull request merged**
