### PR TITLE
Getting started tutorial

### LINKED ISSUE #727: Expand getting started page to a tutorial
Currently the getting started page provide a minimal set of links and leads to the Samples repo. Ideally, Dapr should include a getting started tutorial which gradually teaches Dapr basic terminology and concepts to visitors new to Dapr. 
Links to more extensive pages on each topic and samples will be included.

Exercises, would use HTTP calls via curl to a Dapr sidecar, making the tutorial code agnostic:

Suggested sections:

- [ ] What is Dapr?
- [ ] Dapr CLI
- [ ] Initialize Dapr
- [ ] Storing a state (use Redis, switch to another store)
- [ ] Service Invocation (invoke another service running in a container)
- [ ] Send messages to other services (pub/sub to a subscriber in a container)
- [ ] Retrieve a secret from a secret store (using the local secret store)
- [ ] The Dapr Dashboard 
- [ ] Next steps section leading to samples, SDK specific code and additional docs

### PR DESCRIPTION
**Pull request by orizohar**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Adding step by step instructions in the "getting-started" section to help users who land here (this is the main CTA link from various places") orient in the getting started how-to articles.

## Issue reference

closes https://github.com/dapr/docs/issues/727

### CODE REVIEW

**Comment by AaronCrawfis** [comment]
I like the simple format of the new page, but my concern is that it is duplicative of the pages within Getting Started.

If our problem is the individual Getting Started pages are too complicated, we should work on simplifying them instead of adding additional content that tries to explain them

**Comment by AaronCrawfis** [comment]
@orizohar latest changes look great. Fixed a couple small grammer issues and added "Step X:" to headings as placemarkers

**Comment by orizohar** [comment]
> @orizohar latest changes look great. Fixed a couple small grammer issues and added "Step X:" to headings as placemarkers

I still want to work on this. A few more changes planned...

**Comment by AaronCrawfis** [comment]
> > @orizohar latest changes look great. Fixed a couple small grammer issues and added "Step X:" to headings as placemarkers
> 
> I still want to work on this. A few more changes planned...

Yep, saw the stubbed out page for create a component. Will mark this PR as draft and will be ready to review when ready

**Review by AaronCrawfis — APPROVED** [review]

**Review by AaronCrawfis — APPROVED** [review]

**Pull request merged**
