### PR TITLE
Link Validation: Microsoft Docs links must not be localized

### PR DESCRIPTION
**Pull request by berndverst**
Updates the link validation to also prohibit pinning of Microsoft Docs links to localized versions

### CODE REVIEW

**Comment by berndverst** [comment]
@greenie-msft @willtsai

**Comment by berndverst** [comment]
Merge this after #1906

**Comment by berndverst** [comment]
This PR is working as intended. Please don't merge yet! #1906 must be merged first.

image

**Comment by berndverst** [comment]
This works now:
image

**Review by greenie-msft — APPROVED** [review]

**Comment by greenie-msft** [comment]
Thanks for this contribution @berndverst!

**Review by willtsai — APPROVED** [review]

**Pull request merged**
