### PR TITLE
fixing typo

### PR DESCRIPTION
**Pull request by VuiDJi**
fixed a typo in word "sentin**a**lMasterName "

### CODE REVIEW

**Review by msfussell — APPROVED** [review]
LGTM. Thanks for catching this!!

**Comment by msfussell** [comment]
@VuiDJi - Will close this PR as this is a duplicate of https://github.com/dapr/docs/pull/3064. Agreed?

**Comment by hhunter-ms** [comment]
Closing as duplicate of #3064  - @VuiDJi let me know if I should reopen

**Comment by VuiDJi** [comment]
@hhunter-ms @msfussell It is not duplicate, because this PR fixs supported-state-stores/setup-redis.md file, #3064 fixes supported-locks/redis-lock.md file.

**Comment by hhunter-ms** [comment]
> @hhunter-ms @msfussell It is not duplicate, because this PR fixs supported-state-stores/setup-redis.md file, #3064 fixes supported-locks/redis-lock.md file.

Ah ok, reopened

**Review by hhunter-ms — APPROVED** [review]

**Pull request merged**
