### PR TITLE
[subscriptions doc] update py, go, and js examples

### PR DESCRIPTION
**Pull request by hhunter-ms**
## Description

Update python, go, and javascript declarative code examples to match yaml example

## Issue reference

#2738

### CODE REVIEW

**Comment by msfussell** [comment]
@hhunter-ms - These are good updates. Did you address the question in the issues from @alert01

**Comment by hhunter-ms** [comment]
@msfussell I'm hoping these updates help answer those questions. Would love feedback @alecor191

**Comment by alecor191** [comment]
Thanks a lot @hhunter-ms for looking into this! 

I have a few questiions about the changes:

- Python changes: should `route='route'` be `route='checkout'` instead, considering that the sample talks about the `/checkout` route?
- Python changes: What was the reason for changing `@app.subscribe(pubsub_name=...` to `@app.subscribe(pubsubname=...`? Isn't `pubsub_name` argument name correct?
- It would be great if we could add an explanation under what circumstances the yaml file (`kind: Subscription`) is required, as for me it worked also without it (see #2738 for details)

**Comment by hhunter-ms** [comment]
> * Python changes: should `route='route'` be `route='checkout'` instead, considering that the sample talks about the `/checkout` route?

I believe so - I'll update that

> * Python changes: What was the reason for changing `@app.subscribe(pubsub_name=...` to `@app.subscribe(pubsubname=...`? Isn't `pubsub_name` argument name correct?

I changed this to match the [subscription example in the pub/sub quickstart for python](https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/#step-3-subscribe-to-topics)... What do you think, @msfussell?

> * It would be great if we could add an explanation under what circumstances the yaml file (`kind: Subscription`) is required, as for me it worked also without it (see [Subscription Methods: Unclear/missing information #2738](https://github.com/dapr/docs/issues/2738) for details)

I'll work on this... Thanks for your feedback @alecor191!

**Comment by hhunter-ms** [comment]
@alecor191 It looks like a lot of the confusion around the declarative subscriptions and why the YAML is important is because the code snippets offered as declarative examples were actually programmatic examples. I'm updating the declarative examples to actually reflect what the code would look like listening to the YAML. 

Hopefully that helps!

**Review by msfussell — APPROVED** [review]
LGTM

**Pull request merged**
