### PR TITLE
Update Workflow API docs to stable

### LINKED ISSUE #3870: [Workflow] Docs enhancements with stable release
Doc updates applicable to workflow going stable. 

- [x] #3869 
- [x] #3868 
- [ ] Add metrics documentation?
- [x] Documentation for making workflow backend a configurable component https://github.com/dapr/docs/issues/3924
- [ ] Python SDK decorators updates (#4410)
- [x] Remove 'beta' from code snippets and docs notes

### PR DESCRIPTION
**Pull request by antontroshin**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Update documentation to use stable Workflow API

## Issue reference

Related PR: https://github.com/dapr/dapr/pull/8253

### CODE REVIEW

**Comment by hhunter-ms** [comment]
The notes in the Workflow docs about Workflow being in beta also need removed: 
- All the docs in [Developing applications/Building blocks/Workflow](https://docs.dapr.io/developing-applications/building-blocks/workflow/) section
- [The API reference doc](https://docs.dapr.io/reference/api/workflow_api/)

Does the code snippet for the actor workflow backend need updated?: https://docs.dapr.io/reference/components-reference/supported-workflow-backend/actor-workflow-backend/

SDK docs and code snippets need updated as well, from each sdk repo:
- [.NET](https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-workflow/dotnet-workflow-howto/)
- [Java](https://docs.dapr.io/developing-applications/sdks/java/java-workflow/java-workflow-howto/)
- [JS](https://docs.dapr.io/developing-applications/sdks/js/js-workflow/)
- [Python](https://docs.dapr.io/developing-applications/sdks/python/python-sdk-extensions/python-workflow-ext/)

**Comment by antontroshin** [comment]
Closing this PR for now, as the Workflows API in runtime will be deprecated and likely removed in the next releases. 
Replaced by Workflows Client.
- https://github.com/dapr/dapr/pull/8299

**Comment by msfussell** [comment]
This should not be closed. The docs need to show the final stable API. The beta API will be left there, but we will not mention this, only for transient compatibility until the v1.16 release.

**Review by hhunter-ms — APPROVED** [review]

**Comment by hhunter-ms** [comment]
merging this - @antontroshin I can address the rest of the workflow going stable updates mentioned in the comment above

**Comment by antontroshin** [comment]
@hhunter-ms @msfussell This PR merge should be reverted. 
There's no Stable API update for Workflows `/v1.0/workflow` in the `1.15` release, as the entire workflow usage is now done through a separate Workflow Client.
As per support policy, the "old" `/v1.0-beta1/workflow` stays for a few releases until SDKs catch up in the new Workflow Client support implementation. Documentation, examples, and quickstarts for the new Workflow Client, are being updated in separate PRs.

**Pull request merged**
