### PR TITLE
Adding pluggable secret store doc

### LINKED ISSUE #3783: [1.12] Secrets store support for pluggable components
Secrets stores APIs can be pluggable components. Need to update
1) https://v1-12.docs.dapr.io/developing-applications/develop-components/pluggable-components/develop-pluggable/ to provide overview of the API
2) Update samples for .NET and also Go (however this can come after 1) above

### PR DESCRIPTION
**Pull request by pravinpushkar**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Added Pluggable component secret store documentation.

## Issue reference 

closes #3783

### CODE REVIEW

**Comment by msfussell** [comment]
@pravinpushkar - Can you also add examples for implementing the .NET and Go components for the secret store, like these?
- https://docs.dapr.io/developing-applications/develop-components/pluggable-components/pluggable-components-sdks/pluggable-components-dotnet/
- https://docs.dapr.io/developing-applications/develop-components/pluggable-components/pluggable-components-sdks/pluggable-components-go/

Also if you check that this sample https://github.com/dapr/samples/tree/master/pluggable-components-dotnet-template still works for the v1.12 release and if so update the readme to say this is still valid for 1.12. That would be a huge bonus and benefit!! Thanks

**Review by hhunter-ms — APPROVED** [review]
lgtm

**Review by msfussell — CHANGES_REQUESTED** [review]
@pravinpushkar - Can you look at my suggestions

**Comment by pravinpushkar** [comment]
@msfussell 

> @pravinpushkar - Can you also add examples for implementing the .NET and Go components for the secret store, like these?
> 
> * https://docs.dapr.io/developing-applications/develop-components/pluggable-components/pluggable-components-sdks/pluggable-components-dotnet/
> * https://docs.dapr.io/developing-applications/develop-components/pluggable-components/pluggable-components-sdks/pluggable-components-go/

We cannot mention the developments usings SDKs yet. The .Net and Go PR for dapr-sandbox repo are under development and I will rebase the PRs as soon as stable runtime version 1.12 gets released. Once these PRs are merged, I can revisit this part of the doc.

Relevant PRs -
1) https://github.com/dapr-sandbox/components-dotnet-sdk/pull/42
2) https://github.com/dapr-sandbox/components-go-sdk/pull/28

> Also if you check that this sample https://github.com/dapr/samples/tree/master/pluggable-components-dotnet-template still works for the v1.12 release and if so update the readme to say this is still valid for 1.12. That would be a huge bonus and benefit!! Thanks

Samples works for 1.12. Just updated the Proto for state store and readme.md to be inline with latest enhancements.

Relevant PR - https://github.com/dapr/samples/pull/164 (This is ready for review/merge)

**Comment by msfussell** [comment]
@pravinpushkar - Really appreciate getting the sample in. Will do the SDK updates later. 
Thanks

**Review by msfussell — APPROVED** [review]
LGTM

**Pull request merged**
