### PR TITLE
updated rabbitmq pub/sub documentation

### PR DESCRIPTION
**Pull request by trondhindenes**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description
Updated rabbitmq documentation to include changes made in https://github.com/dapr/components-contrib/pull/562. Also changes the format to use the new https://v1-rc2.docs.dapr.io/operations/components/component-schema/ one.

## Issue reference
N/A

### CODE REVIEW

**Comment by trondhindenes** [comment]
btw I'm not sure if I should include the "global" fields (`apiVersion, kind, metadata.name`) etc in this PR. They're in the component schema (https://v1-rc2.docs.dapr.io/operations/components/component-schema/), but it's not quite clear to me if every component documentation should copy this. It would be awesome to have "template" to look at for component documentation.

**Comment by AaronCrawfis** [comment]
@trondhindenes did the change to components-contrib make it into the rc2 release (and therefore applies to the rc2 docs)? Or is it only applicable to the upcoming rc3 release and docs?

**Comment by AaronCrawfis** [comment]
Oh I actually am just now reading your note on [Discord](https://discord.com/channels/778680217417809931/778684392893579267/795306871770185749) regarding this exact problem. Will get back shortly on that.

**Comment by trondhindenes** [comment]
> did the change to components-contrib make it into the rc2 release?

I'm pretty sure it targets rc3, but I'm not sure how to find out for certain.

**Comment by yaron2** [comment]
~It made it into rc.2~

**Comment by yaron2** [comment]
Sorry, this was NOT included in rc.2.

**Comment by yaron2** [comment]
@trondhindenes please resolve the conflict, which you will find familiar :)

**Comment by msfussell** [comment]
This format is very nice. Let's start rolling this out across all components. We should include all the global fields as developers should be able to cut and past the file and just use this with the Metadata settings of their choice.  I especially like the examples column, which is often where people get stuck

Some comments on your changes.
1) deleteWhenUnused defaults to "true" not "false" as set the table.
2) The Durable property is not in the metadata struct, so should be removed from the table.
3) The default reconnectWait time is 10s. This is not mentioned as the default in the table.

**Comment by trondhindenes** [comment]
@msfussell thanks!
I totally agree that the yaml codeblock should be "copyable" directly. My question was whether or not it makes sense to document the "global" fields (`apiVersion`, `kind` etc) in the fields table. My opinion is that no, that doesn't make sense as it only bloats the table (this is also where this PR differs from the https://v1-rc2.docs.dapr.io/operations/components/component-schema/).

Thanks for looking thru the actual content - will correct.

**Comment by msfussell** [comment]
@trondhindenes - Yes, do not include the general component schema, simply reference this in the related links like this - [Basic schema for a Dapr component]({{< ref component-schema >}})

can you push the suggest changes so that we can merge this PR?

**Review by msfussell — COMMENTED** [review]
@trondhindenes 
Add - [Basic schema for a Dapr component]({{< ref component-schema >}}) in the Related links section
Change "Fields" heading to "Spec metadata fields"

**Comment by msfussell** [comment]
@trondhindenes  - Any chance you can push an update to this PR, since we would like to get this in. 
You can see your new proposed format here https://v1-rc3.docs.dapr.io/operations/components/setup-pubsub/supported-pubsub/setup-redis-pubsub/

**Comment by msfussell** [comment]
@trondhindenes - I updated the PR in your branch for all the changes. You just need to review these and ACK. 
This PR goes with this issue https://github.com/dapr/docs/issues/1084

**Comment by trondhindenes** [comment]
@msfussell sorry for being so slow on this one. I'm fine with the changes you've made. I've resolved the conflict, and also added documentation for the concurrency setting that @yaron2 added a few days ago. Hopefully this is ready to merge now!

**Review by AaronCrawfis — APPROVED** [review]

**Pull request merged**
