### PR TITLE
Deficiencies in the steps updated with the multi-app run feature that comes with v12

### PR DESCRIPTION
**Pull request by baransonmez**
## Description
As mentioned in the Issue #3860 , there were deficiencies in the steps of the newly added multi-app run feature. Generally, the step of installing dependencies in the state-management header was skipped. In this PR, I added this step to the relevant points.  

In addition, I made an extra note for the python3 problem in windows environments and informed the developers who will follow the document. 

## Issue reference
#3860

### CODE REVIEW

**Comment by hhunter-ms** [comment]
FYI @mukundansundar - need to merge dapr/quickstarts#955 first

**Comment by baransonmez** [comment]
Hello again, I completed the issue a few weeks ago but I am not aware if there is any extra work I need to do. Is there a point I missed? When I looked at the Github Actions, I understood that it's just waiting for the reviewer to check it, but I still wanted to ask to be sure.

**Comment by hhunter-ms** [comment]
@baransonmez sorry about the delay, I'm working on getting the code PR in the quickstart repo to go through

**Comment by baransonmez** [comment]
Oh, I see. Well, if there's anything I can do, I'd like to help. Thank you for your quick response and interest @hhunter-ms

**Review by yaron2 — APPROVED** [review]

**Comment by baransonmez** [comment]
I merged 'v1.12' into this branch, do I need to do anything for the workflow to progress?

**Pull request merged**
