### PR TITLE
Upgrade Java pre-req on QuickStarts to JDK 17

### LINKED ISSUE #4222: Wrong Java required version in documentation for Quickstart
**Wrong Java min version**

The documentation for the quickstart says "Java JDK 11 (or greater)". However the code for checkout and order processor requires Java 17

```
<java.version>17</java.version>
```

```
<maven.compiler.source>17</maven.compiler.source>
<maven.compiler.target>17</maven.compiler.target>
```

**URL of the docs**

https://docs.dapr.io/getting-started/quickstarts/serviceinvocation-quickstart/

**Expected content**

Java JDK 17
instead of
Java JDK 11 (or greater)

It cannot be "Java JDK 17 **(or greater)**" because the Lombok version included in spring boot 2.x is not compatible with Java 21 and it should be upgraded (upgrading manually the lombok version to 1.18.30, replacing the one in the spring boot BOM, it works with Java 21). This version is therefore locked to Java 17, not lower, not greater

### PR DESCRIPTION
**Pull request by salaboy**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Upgrading quickstarst pre requisites to Java SDK 17 from 11. 

## Issue reference

Closes #4222

### CODE REVIEW

**Comment by salaboy** [comment]
@msfussell @artursouza please review and approve

**Comment by hhunter-ms** [comment]
Docs are waiting on dapr/quickstarts#1042 to be merged

**Comment by salaboy** [comment]
@hhunter-ms thanks for the mention, I've reviewed the pending PR and approved.. I think that it is waiting for one more approval

**Review by msfussell — APPROVED** [review]
This can now be merged given the quickstart PR is merged

**Pull request merged**
