### PR TITLE
Refactor supported component pages, refactor secret store docs

### PR DESCRIPTION
**Pull request by mukundansundar**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Fix the binding, pubsub, state store and secretstore supported list pages. 

Fix NATS Streaming metadata fields list. 

Refactored Secret Store Docs.

### CODE REVIEW

**Comment by AaronCrawfis** [comment]
@mukundansundar Could you add an alias to the setup-gcp-pubsub.md page so any external links still work? https://gohugo.io/content-management/urls/#aliases

**Review by AaronCrawfis — APPROVED** [review]

**Review by msfussell — APPROVED** [review]
LGTM

**Comment by msfussell** [comment]
@orizohar - Hold on merging this PR yet, even though this is approved

**Review by msfussell — APPROVED** [review]
All these updates look good.

**Comment by msfussell** [comment]
All these updates look good.

**Pull request merged**
