### PR TITLE
Updates to Stable component process.

### PR DESCRIPTION
**Pull request by artursouza**
Signed-off-by: Artur Souza <artursouza.ms@outlook.com>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Adds `stable candidate`  step.
Changes requirement from 1 to 2 approvers for component to be stable.

### CODE REVIEW

**Review by berndverst — APPROVED** [review]

**Comment by msfussell** [comment]
Have all Component  Contrib maintainers agreed to this?

**Comment by berndverst** [comment]
I would say we should get the approval of two contrib maintainers to call something stable, but needing to maintainers to merge a PR in certification tests doesn't seem like a good idea.

We should refine the details a little bit here.

Can we have a yaml file at the root of contrib where we track what is stable and then require two maintainers to modify that file?

**Comment by greenie-msft** [comment]
@berndverst, @artursouza, @yaron2  - have we come to an agreement here with how to handle stable candidates

**Comment by berndverst** [comment]
@greenie-msft we have not - we need to separately discuss this. And that does not need to happen timed with release 1.8

Personally I think we should do this:
- Keep a file in the contrib repo of stable components. Modifying that file requires 2 maintainers to approve / author the PR.
- Certification tests themselves however will continue to require one maintainer as before. This is important because I want to decouple the development (especially iterative development) of certification tests from the actual stable certification.

**Comment by msfussell** [comment]
> @greenie-msft we have not - we need to separately discuss this. And that does not need to happen timed with release 1.8
> 
> Personally I think we should do this:
> 
> * Keep a file in the contrib repo of stable components. Modifying that file requires 2 maintainers to approve / author the PR.
> * Certification tests themselves however will continue to require one maintainer as before. This is important because I want to decouple the development (especially iterative development) of certification tests from the actual stable certification.

For the first point, can we use these https://github.com/dapr/docs/tree/v1.7/daprdocs/data/components since this is what John did this for in the docs?

**Comment by berndverst** [comment]
> > @greenie-msft we have not - we need to separately discuss this. And that does not need to happen timed with release 1.8
> > Personally I think we should do this:
> > 
> > * Keep a file in the contrib repo of stable components. Modifying that file requires 2 maintainers to approve / author the PR.
> > * Certification tests themselves however will continue to require one maintainer as before. This is important because I want to decouple the development (especially iterative development) of certification tests from the actual stable certification.
> 
> For the first point, can we use these https://github.com/dapr/docs/tree/v1.7/daprdocs/data/components since this is what John did this for in the docs?

@greenie-msft I really want that to be separate from documentation that is shown. It should be more of an internal file to keep track of technical decision-making.

As long as we set up the permissions such that ONLY contrib maintainers can provide reviews and approvals for that file (via CODEOWNERS) I'm fine with having this anywhere. Even Docs maintainers should not be allowed to approve changes to this. That's the entire point - our tooling must enforce that two contrib maintainers are involved.

**Comment by artursouza** [comment]
This is not applicable anymore since we do not require stable candidates.

**Pull request closed without merging**
