### PR TITLE
Update php docs for 1.6

### LINKED ISSUE #115: Update dapr docs with 1.2 changes
## Release Note

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by withinboredom**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

This updates the PHP SDK docs for PHP SDK v1.2 and Dapr 1.6

## Issue reference

PHP SDK PR: dapr/php-sdk#124
Closes: dapr/php-sdk#115

### CODE REVIEW

**Comment by withinboredom** [comment]
Failing link validation doesn't look related to this PR.

**Comment by msfussell** [comment]
@withinboredom - We should get https://github.com/dapr/docs/pull/2026 in first and then you can apply these PHP changes.

**Comment by withinboredom** [comment]
Awesome, thanks!

**Comment by withinboredom** [comment]
I'm not well versed in how to fix the merge conflicts here with this flow. I'll probably get to this next weekend.

**Comment by msfussell** [comment]
@withinboredom #2026 is now in, so you can merge your changes

**Comment by greenie-msft** [comment]
Hi @withinboredom,

With the recent addition of https://github.com/dapr/docs/pull/2026, all SDK examples per building block follow the same scenario (two services Order and Checkout). Is it possible to modify the PHP examples to follow the other SDKs?

A description of the scenario can be found at the top of every how-to page for each building block. E.g.  Service Invocation: https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/#example

If possible, consider making these changes  on a new branch to avoid merge conflicts.

Thank you.

**Comment by greenie-msft** [comment]
@withinboredom Can we find some time to chat about this PR and how we can get this into the docs? It's been roughly a month with no activity on this so we'll need to close this PR soon.

**Comment by msfussell** [comment]
@withinboredom - I suggest closing this PR, and chatting on what next for PHP since there are significant changes we have done to the quickstarts.

**Comment by greenie-msft** [comment]
Closing as this PR has become very stale. Please open a new PR if you would like to get these change in

**Pull request closed without merging**
