### PR TITLE
feature/pubsub: add delay queue params for pulsar

### PR DESCRIPTION
**Pull request by 1046102779**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

### CODE REVIEW

**Comment by orizohar** [comment]
@1046102779  There is no issue for this PR. What is the nature of the change? is this missing information in an existing page? new functionality that was added in a code PR? please provide more information and links to relevant issue/code PR.

**Comment by msfussell** [comment]
This is for https://github.com/dapr/components-contrib/pull/1112 and needs to be included into the v1.4 docs.

**Comment by yaron2** [comment]
@orizohar @AaronCrawfis per @msfussell can this get reviewed? Thanks

**Comment by orizohar** [comment]
> @orizohar @AaronCrawfis per @msfussell can this get reviewed? Thanks

@yaron2  Looks like the code PR is still open. Since we are past code freeze for v1.4, should this be merged to v1.5 instead?

**Comment by greenie-msft** [comment]
@1046102779 Can you please update the base branch of this PR to 1.5? Thank you.

**Review by msfussell — COMMENTED** [review]
@1046102779 - Per request from @greenie-msft can you target v1.5 docs branch?

**Comment by willtsai** [comment]
@1046102779 - Reminding again. Per request from @greenie-msft can you target v1.5 docs branch?

**Comment by 1046102779** [comment]
> @1046102779 Can you please update the base branch of this PR to 1.5? Thank you.

sorry, the PR has been resubmitted.

**Comment by willtsai** [comment]
This PR can be closed in favor of the new PR targeting v1.5 for the same changes: https://github.com/dapr/docs/pull/1759

**Comment by greenie-msft** [comment]
Closing this stale PR in favor of: https://github.com/dapr/docs/pull/1856

**Pull request closed without merging**
