### PR TITLE
feature/pulsar: provide token && http request

### PR DESCRIPTION
**Pull request by 1046102779**
patch DCO.

https://github.com/dapr/docs/pull/2090

https://github.com/dapr/components-contrib/pull/1427

### CODE REVIEW

**Comment by 1046102779** [comment]
@msfussell +1

**Review by msfussell — APPROVED** [review]
LGTM

**Comment by msfussell** [comment]
@1046102779 - I add a link to the pulsar docs. However it looks like the DCO is failing. Can you sign the commit request? Like this
git commit -m "my update" -s

**Comment by msfussell** [comment]
@1046102779 we are locking down the v1.6 release and need to get these docs in. Can  you sign the DCO?

**Pull request merged**
