### PR TITLE
Update JS-SDK docs

### LINKED ISSUE #2498: Update JS SubModule
**Describe the issue**

Bump JS Submodule to the latest version

### PR DESCRIPTION
**Pull request by shubham1172**
Signed-off-by: Shubham Sharma <shubhash@microsoft.com>

Point JS-SDK to the latest commits.

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting: **
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [X] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Updated the submodule `sdkdocs/js`

## Issue reference

Closes #2498

### CODE REVIEW

**Comment by msfussell** [comment]
@shubham1172 - i see that you put WIP. When can I do this PR merge?

**Comment by shubham1172** [comment]
@msfussell we will release a new version by tomorrow, post which I will update the docs as needed and remove WIP!

**Comment by msfussell** [comment]
@shubham1172 - can we merge this now and then do another later?

**Comment by shubham1172** [comment]
Yes, we can do that (FYI @XavierGeerinck). FYI v2.3.0 has been released and we are good for this PR.

**Review by greenie-msft — APPROVED** [review]

**Review by msfussell — APPROVED** [review]
LGTM

**Pull request merged**
