### PR TITLE
Workflow terminate/purge: remove `non_recursive` query option

### PR DESCRIPTION
**Pull request by JoshVanL**
Updates from PR https://github.com/dapr/dapr/pull/7498

### CODE REVIEW

**Comment by msfussell** [comment]
@JoshVanL - Looks great. Set to waiting on Code PR before merging.

**Comment by JoshVanL** [comment]
@msfussell please note the PR is updated to now remove the query completely after discussion on https://github.com/dapr/dapr/pull/7498

**Comment by msfussell** [comment]
> @msfussell please note the PR is updated to now remove the query completely after discussion on [dapr/dapr#7498](https://github.com/dapr/dapr/pull/7498)

For the recursive purge, we decide to remove the setting altogether, it that it always does this? Just making sure I understand this correctly. This statement "Removes this option so that recursive is always enabled with no API field exposing the option."

**Review by shivamkm07 — APPROVED** [review]

**Comment by JoshVanL** [comment]
@msfussell correct, the option has been completely removed, and workflow deletion will always be done recursively. This option can be added back in future if we decide it is needed.

**Review by hhunter-ms — APPROVED** [review]

**Pull request merged**
