### PR TITLE
fix: add a link to a better cron binding example.

### PR DESCRIPTION
**Pull request by swuecho**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

The doc about cron binding is too dry. If possible, the whole blog should be append at the end (in case the blog is down). 

disclaimer: I am not the author of the blog article.

### CODE REVIEW

**Comment by msfussell** [comment]
@swuecho - can I suggest that in this case, that you pull the content into the Dapr Docs and this topic. The main difference seems to be a description on how to use the binding and the code example. This would be better for readers, since the article extends the sample in the doc in the first place. Thanks

**Comment by swuecho** [comment]
@msfussell  I was thinking the same, but not sure about the licence issues.

@markheath Could you kindly put the content into the doc? That will be perfect.

**Comment by willtsai** [comment]
@swuecho - could you please add the content you'd like to see directly into the page instead of linking out to another doc? A simple rewrite of the concepts would work.

**Comment by markheath** [comment]
I'm happy for you to borrow any content from my blog post to update the docs

**Comment by swuecho** [comment]
> I'm happy for you to borrow any content from my blog post to update the docs

Thanks for your generosity. I will update the doc soon

**Pull request closed without merging**
