### PR TITLE
fixing missing policies for sns and sqs

### LINKED ISSUE #2206: Permissions for AWS IAM Policy do not suffice to let Dapr auto provision AWS resources for SQS/SNS pub sub
**Describe the issue**
These example permissions do not suffice for letting Dapr auto provision the required AWS resources. So far I found that these permissions are missing:
- sns:TagResource
- sqs:SendMessage
- sqs:TagQueue

There is a duplicate permission entry for sns:ListSubscriptionsByTopic permission. (minor)

**URL of the docs**
[url](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-aws-snssqs/)

**Expected content**
The required permissions, including sns:TagResource. Even with this permission it still gives me a Unauthorized response through Dapr logs, but it remains unclear through the response or CloudTrail that the missing permission is.

**Screenshots**
When I boot up the app and the sidecar I get the following logs:
`level=error msg="failed to subscribe to topic mws-messages-some-events-initialphoneverificationcompletedevent: error getting topic ARN for mws-messages-some-events-initialphoneverificationcompletedevent: error while creating an SNS topic: AuthorizationError: User: arn:aws:iam::************:user/dapr-local-sqs-test is not authorized to perform: SNS:TagResource on resource: arn:aws:sns:eu-west-1:************:mws-messages-some-events-initialphoneverificationcompletedevent because no some-based policy allows the SNS:TagResource action\n\tstatus code: 403, request id: 3c510feb-18f8-5ad8-8fc5-6665ab783b80" app_id=mws-some-webapp instance=589cb03abcfc scope=dapr.runtime type=log ver=1.6.0`

**Additional context**
From the IAM control panel my permissions look like these:
```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "sqs:DeleteMessage",
                "sqs:GetQueueUrl",
                "sns:ListSubscriptionsByTopic",
                "sqs:ChangeMessageVisibility",
                "sns:GetTopicAttributes",
                "sqs:ReceiveMessage",
                "sns:CreateTopic",
                "sqs:GetQueueAttributes",
                "sns:UntagResource",
                "sns:Publish",
                "sns:Subscribe",
                "sqs:CreateQueue",
                "sqs:SetQueueAttributes"
            ],
            "Resource": [
                "arn:aws:sns:eu-west-1:************:*",
                "arn:aws:sqs:eu-west-1:************:*"
            ]
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by amimimor**
Signed-off-by: Amit Mor <amitm@at-bay.com>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Added to the AWS setup section related to IAM policy for PubSub SNS/SQS 2 missing entries that without them the sidecar fails to create the relevant assets.
Sorted the list of permissions for better deduplication and readability

### CODE REVIEW

**Review by ianbeemsterboerr — CHANGES_REQUESTED** [review]
It's missing the sqs:SendMessage permission. (if I compare this to the example in Discord)

**Comment by amimimor** [comment]
> It's missing the sqs:SendMessage permission. (if I compare this to the example in Discord)

It isn't needed for this component since the only way the sidecar publishes messages is through SNS. The message then arrives to SQS using an SQS subscription to SNS

**Comment by msfussell** [comment]
@amimimor - Did you want this to target the next docs release, or go into the current v1.6 docs?

**Comment by ianbeemsterboerr** [comment]
These permissions already apply to version 1.6, but the docs don't yet reflect this, so I think it should be applied to 1.6 docs

**Comment by amimimor** [comment]
@msfussell  @ianbeemsterboerr I've opened the PR to be merged into 1.7 because I thought that 1.6 docs are already published and cannot be amended. If this edit can be added to 1.6 then it would sure be welcomed

**Comment by msfussell** [comment]
@amimimor v1.6 is the live branch for dapr.docs.io. Please target v1.6 branch as the base branch for the current docs for this PR

**Comment by amimimor** [comment]
> @amimimor v1.6 is the live branch for dapr.docs.io. Please target v1.6 branch as the base branch for the current docs for this PR

@msfussell I've tried switching but I don't want to reset and generally get into a fight with git (would have been differences in 14 files against v1.6). Is it ok I'd open another PR instead of this for merging against v1.6?

**Comment by msfussell** [comment]
Yes. Just close this PR and open a new one on v1.6. We then upmerge from v1.6 to v1.7

**Comment by msfussell** [comment]
@amimimor - can you open a new PR on v1.6? Thanks

**Comment by greenie-msft** [comment]
@amimimor we will merge this in 1.7, but would appreciate if you could also create the same PR for 1.6 branch. Thank you

**Review by greenie-msft — APPROVED** [review]

**Pull request merged**
