### PR TITLE
Added endpoint details for event triggers.

### PR DESCRIPTION
**Pull request by jocko-wowza**
# Description

Added a section to the inbound bindings documentation that describes how to trigger an event.

While referencing the example briefly in the head of the inbound bindings documentation, the doc was not explicit about how to actually trigger an event. 

## Issue reference

Issue #85 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [N/A] Code compiles correctly
* [N/A] Created/updated tests
* [X] Extended the documentation

### CODE REVIEW

**Comment by yaron2** [comment]
He @jocko-wowza, first of all, thanks for this PR!

However, have you seen this how-to for *output* bindings?
https://github.com/dapr/docs/tree/master/howto/send-events-with-output-bindings

This how-to describes output bindings, while the one you extended is solely focused on input bindings.

**Comment by jocko-wowza** [comment]
Maybe I mis-typed something, but what I was reacting to was Input Bindings, not Output bindings, and that it was hard to find the right endpoint to send a binding trigger to when operating in the context of an Input Binding.

**Comment by jocko-wowza** [comment]
I just realized that pull request also includes the other change we are discussing.  Apologies for that.

**Comment by yaron2** [comment]
> I just realized that pull request also includes the other change we are discussing. Apologies for that.

Lets merge the other PR first and then continue to discuss this one..

**Comment by jocko-wowza** [comment]
So with your comments above and the documentation, am I to understand that the articles:

- https://github.com/dapr/docs/tree/master/howto/trigger-app-with-input-binding
- https://github.com/dapr/docs/tree/master/howto/send-events-with-output-bindings

Are two halves of a workflow where you define an input-binding to react to an event trigger, and then call an output-binding to trigger that event?

**Comment by yaron2** [comment]
> So with your comments above and the documentation, am I to understand that the articles:
> 
> * https://github.com/dapr/docs/tree/master/howto/trigger-app-with-input-binding
> * https://github.com/dapr/docs/tree/master/howto/send-events-with-output-bindings
> 
> Are two halves of a workflow where you define an input-binding to react to an event trigger, and then call an output-binding to trigger that event?

Not necessarily that specific event, but yes, you are right: the first one teaches you on how to listen for input binding events, and the second one complements it by teaching you how to invoke output bindings.

The bindings *sample* ties the two together.

**Comment by jocko-wowza** [comment]
Okay ... So as feedback, I read them as being two different conceptual forms of bindings.   Perhaps the input binding documentation could reference the Output binding documentation at the end instead.   If you want I can write it up and do another pull request.

**Comment by yaron2** [comment]
> Okay ... So as feedback, I read them as being two different conceptual forms of bindings. Perhaps the input binding documentation could reference the Output binding documentation at the end instead. If you want I can write it up and do another pull request.

Sounds good. it'd be best to insert a small section at the end of the input bindings how-to that links up to the output bindings one as continuity.

**Comment by jocko-wowza** [comment]
Fixed in another PR. Closing

**Pull request closed without merging**
