### PR TITLE
Update Chinese translated content to v1.1

### PR DESCRIPTION
**Pull request by newbe36524**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

- update latest source content from  v1.1
- update latest translation to v1.1

### CODE REVIEW

**Comment by newbe36524** [comment]
@skyao could you please help to review this content ? many thanks.

**Review by AaronCrawfis — CHANGES_REQUESTED** [review]
Please make sure there are no `aliases` in the front-matter of any pages. I saw a couple in the 1.1 branch of the docs-zh repo.

**Comment by newbe36524** [comment]
@AaronCrawfis  I wonder that why it is need to be done those are copied from source file.

Do you think it is ok if I just translated aliases into a url with /zh-hans/ prefix rather than delete them?
You know, to delete them will be manually work for us but to translate them will be easy.

Could you please give me more details about this issue and I can sharing it to my partners.

**Comment by AaronCrawfis** [comment]
> @AaronCrawfis I wonder that why it is need to be done those are copied from source file.
> 
> Do you think it is ok if I just translated aliases into a url with /zh-hans/ prefix rather than delete them?
> You know, to delete them will be manually work for us but to translate them will be easy.
> 
> Could you please give me more details about this issue and I can sharing it to my partners.

@newbe36524 aliases cause issues in Hugo for translations. We add aliases to the English docs anytime we move documentation from one location to another, so that outside bookmarks and links don't break. It acts as a redirect, where if someone navigates to the alias they will instead be redirected to the new path.

If there is an alias in both the English and Chinese docs, Hugo for some reason picks the Chinese version to redirect to. For example, if there is an alias `/my-alias/path`, and a user navigates to https://docs.dapr.io/my-alias/path, they will instead be redirected to the Chinese docs. Original issue here: #1336 

Since Chinese users wouldn't have bookmarks to old versions of the docs, ideally we would delete the aliases in the Chinese translations. However, since it involves work translating the aliases may work. We would need to test that Chinese characters in aliases wouldn't break Hugo or the site since they're translated into URLs. We also need to make sure pages that haven't been translated yet don't contain aliases.

**Comment by AaronCrawfis** [comment]
More information here: https://github.com/gohugoio/hugo/issues/2452

**Comment by newbe36524** [comment]
@AaronCrawfis Thank you very much for being able to provide such detailed information.
I have synced the solution to this issue with the team members to all of them.
In the future, we will prefix these alias with /zh-hans/ to make sure there is no conflict with the en content.
We have verified that this works.
The latest content has been revised up, if you have any questions then feel free to ask.

**Review by AaronCrawfis — APPROVED** [review]

**Pull request merged**
