### PR TITLE
[Pluggable components] Add secrets and config support

### PR DESCRIPTION
**Pull request by hhunter-ms**
## Description

Adding secrets and config support for v1.10 in pluggable components

## Issue reference

Related PR: dapr/dapr#5513

### CODE REVIEW

**Comment by hhunter-ms** [comment]
@philliphoff - FYI

**Comment by nyemade-uversky** [comment]
@hhunter-ms  for 1.10 we're just adding .NET SDKs for state store, pub sub and bindings pluggable components. We aren't going to be supporting secret stores or config stores for this release, that'll probably be in 1.11.

**Comment by hhunter-ms** [comment]
@nyemade-uversky ok sounds good. I misunderstood what was needed for docs... Can you clarify this docs need mentioned in the issue?
> Docs exists for the new Secret/Config API functionality (update [overview page](https://docs.dapr.io/operations/components/pluggable-components/pluggable-components-overview/))

**Comment by nyemade-uversky** [comment]
@hhunter-ms  Sure thing! We removed a few things that wouldn't make it into the release for 1.10 (secret store/config) and I forgot to update it on this issue. 

For now the only docs needed are those for the .NET SDKs for pluggable components and those SDKs will live in the dapr-sandbox repo. The docs for those SDKs will live there too with the code so there's nothing for you to work on - @philliphoff can work on those docs.

**Comment by hhunter-ms** [comment]
@nyemade-uversky Sounds good! I'll close this then, thank for the clarification!

**Pull request closed without merging**
