### PR TITLE
Add example for nats jetstream with nkey based authentication

### PR DESCRIPTION
**Pull request by gehhilfe**
Signed-off-by: Tim Burkert <burkert.tim@gmail.com>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x]  Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Updated nats jetstream pub-sub components reference with new metadata fields for decentralized JWT Authentication

### CODE REVIEW

**Comment by gehhilfe** [comment]
I think it's moved to 1.7

**Comment by msfussell** [comment]
@Gehhilfe I see. The code PR is now going to be merged in v1.7.
One consideration to add to the docs, is links to the nats jetstream on how to use the nkey  auth. This just always helps people understand exactly what they need to do. Q: Is it useful to add a link to the Nats nkey docs?

**Comment by gehhilfe** [comment]
@msfussell Sorry for the late response. I will add some more documentation and references to nats documentation.

**Comment by gehhilfe** [comment]
Added a link to nats documentation

**Comment by msfussell** [comment]
@Gehhilfe Can you target the v1.7 docs branch for this PR? Thanks

**Pull request closed without merging**
