### PR TITLE
updated RabbitMQ Pub/Sub status

### PR DESCRIPTION
**Pull request by dmitsh**
Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

### CODE REVIEW

**Review by artursouza — APPROVED** [review]

**Comment by yaron2** [comment]
I am weary of declaring this as stable when this is unresolved: https://github.com/dapr/components-contrib/issues/826

cc @artursouza

**Comment by dmitsh** [comment]
> I am weary of declaring this as stable when this is unresolved: [dapr/components-contrib#826](https://github.com/dapr/components-contrib/issues/826)
> 
> cc @artursouza

I could not reproduce this issue anymore in v1.5.1 with my setup.
I asked the author to try and reproduce the issue at their side, but didn't get any response yet.

**Comment by yaron2** [comment]
> > I am weary of declaring this as stable when this is unresolved: [dapr/components-contrib#826](https://github.com/dapr/components-contrib/issues/826)
> > cc @artursouza
> 
> I could not reproduce this issue anymore in v1.5.1 with my setup. I asked the author to try and reproduce the issue at their side, but didn't get any response yet.

I understand, however we have *2* end users reporting this. The workaround to go to a pub/sub component per topic does not allow this component to become stable, and so the question arises of whether we'd like to wait for confirmation before marking this as stable, and moving this to `Beta` instead.

Going back from stable to `beta` is very ill advised..

**Comment by msfussell** [comment]
Maybe I missed this, but where is the assessment for this component that this is deemed as stable? Does is satisfy this?

Beta
The component must pass all the component conformance tests defined to satisfy the component specification
The component conformance tests have been run in a Dapr maintainers managed environment
The component contains a record of the conformance test result reviewed and approved by Dapr maintainers with specific components-contrib version
Recommended for only non-business-critical uses because of potential for incompatible changes in subsequent releases

Stable
The component must have component certification tests validating functionality and resiliency
The component is maintained by Dapr maintainers and supported by the community
The component is well documented and tested
A maintainer will address component security, core functionality and test issues according to the Dapr support policy and issue a patch release that includes the patched stable component

**Comment by dmitsh** [comment]
> Maybe I missed this, but where is the assessment for this component that this is deemed as stable? Does is satisfy this?
> 
> Beta The component must pass all the component conformance tests defined to satisfy the component specification The component conformance tests have been run in a Dapr maintainers managed environment The component contains a record of the conformance test result reviewed and approved by Dapr maintainers with specific components-contrib version Recommended for only non-business-critical uses because of potential for incompatible changes in subsequent releases
> 
> Stable The component must have component certification tests validating functionality and resiliency The component is maintained by Dapr maintainers and supported by the community The component is well documented and tested A maintainer will address component security, core functionality and test issues according to the Dapr support policy and issue a patch release that includes the patched stable component

Per description above RabbitMQ Pub/Sub component satisfies `stable` requirements, but I'm ok to wait for user's feedback. There is no rush to declare it `stable`.

**Comment by msfussell** [comment]
> Per description above RabbitMQ Pub/Sub component satisfies `stable` requirements, but I'm ok to wait for user's feedback. There is no rush to declare it `stable`.

I guess my ask is that a Component Repo maintainer (possibly approver) must "sign-off" on the criteria above at some point in an issue to say this as a point of record otherwise anyone can say this. 

For now shall we mark this as Beta here, and is we do it would be good to record the status changes in the issue in Component Contrib, approved by @artursouza  or @yaron2

**Comment by dmitsh** [comment]
> > Per description above RabbitMQ Pub/Sub component satisfies `stable` requirements, but I'm ok to wait for user's feedback. There is no rush to declare it `stable`.
> 
> I guess my ask is that a Component Repo maintainer (possibly approver) must "sign-off" on the criteria above at some point in an issue to say this as a point of record otherwise anyone can say this.
> 
> For now shall we mark this as Beta here, and is we do it would be good to record the status changes in the issue in Component Contrib, approved by @artursouza or @yaron2

Not sure I understand the reasoning.
The certification test plan has been submitted, reviewed, and approved (https://github.com/dapr/components-contrib/issues/954). The certification test has been implemented, reviewed, approved, and merged (https://github.com/dapr/components-contrib/pull/1278).
The certification tests are passing, which IIUC is the criteria for graduating a component to `stable`.
If this criteria is different, I wasn't aware of that.

**Comment by artursouza** [comment]
> > > Per description above RabbitMQ Pub/Sub component satisfies `stable` requirements, but I'm ok to wait for user's feedback. There is no rush to declare it `stable`.
> > 
> > 
> > I guess my ask is that a Component Repo maintainer (possibly approver) must "sign-off" on the criteria above at some point in an issue to say this as a point of record otherwise anyone can say this.
> > For now shall we mark this as Beta here, and is we do it would be good to record the status changes in the issue in Component Contrib, approved by @artursouza or @yaron2
> 
> Not sure I understand the reasoning. The certification test plan has been submitted, reviewed, and approved ([dapr/components-contrib#954](https://github.com/dapr/components-contrib/issues/954)). The certification test has been implemented, reviewed, approved, and merged ([dapr/components-contrib#1278](https://github.com/dapr/components-contrib/pull/1278)). The certification tests are passing, which IIUC is the criteria for graduating a component to `stable`. If this criteria is different, I wasn't aware of that.

Dmitry followed the whole process for stable certification and made sure the issue reported was not reproducible anymore after the hotfix. We can add a new criterion about "Make sure P0s and P1s issues on the component are resolved." - which Dmitry did but we can decide to wait on users to get back to us within 2 or 3 days. Again, we need to be careful not to be in another situation where we cannot mark components as stable because users did not reply back anymore. "Stable components" do not mean "bug free components" - bug exists and we fix those as they are reported.

**Comment by yaron2** [comment]
> > > > Per description above RabbitMQ Pub/Sub component satisfies `stable` requirements, but I'm ok to wait for user's feedback. There is no rush to declare it `stable`.
> > > 
> > > 
> > > I guess my ask is that a Component Repo maintainer (possibly approver) must "sign-off" on the criteria above at some point in an issue to say this as a point of record otherwise anyone can say this.
> > > For now shall we mark this as Beta here, and is we do it would be good to record the status changes in the issue in Component Contrib, approved by @artursouza or @yaron2
> > 
> > 
> > Not sure I understand the reasoning. The certification test plan has been submitted, reviewed, and approved ([dapr/components-contrib#954](https://github.com/dapr/components-contrib/issues/954)). The certification test has been implemented, reviewed, approved, and merged ([dapr/components-contrib#1278](https://github.com/dapr/components-contrib/pull/1278)). The certification tests are passing, which IIUC is the criteria for graduating a component to `stable`. If this criteria is different, I wasn't aware of that.
> 
> Dmitry followed the whole process for stable certification and made sure the issue reported was not reproducible anymore after the hotfix. We can add a new criterion about "Make sure P0s and P1s issues on the component are resolved." - which Dmitry did but we can decide to wait on users to get back to us within 2 or 3 days. Again, we need to be careful not to be in another situation where we cannot mark components as stable because users did not reply back anymore. "Stable components" do not mean "bug free components" - bug exists and we fix those as they are reported.

I agree with that, generally. Again, the issue for this component means users cannot create more than one topic per component, which is a major issue that cannot allow it to become stable. So while the process you describe is good in general, every component still has its own distinct set of issues that must be looked at.

Waiting several more days for a user to report back and play it safe is much better imo than rushing an approval process that is very hard to backtrack.

**Comment by dmitsh** [comment]
Got response from the issue author:
https://github.com/dapr/components-contrib/issues/826#issuecomment-989780634

**Pull request closed without merging**
