### PR TITLE
Added Event Grid Binding Spec

### PR DESCRIPTION
**Pull request by lynn-orrell**
# Description

Added event grid binding spec doc

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [x] Extended the documentation

### CODE REVIEW

**Comment by Masahigo** [comment]
Hi,

I would like to see some more documentation on this one.

I tried to follow these instructions for implementing an Event Grid input binding for .NET core web api but they fall short on couple of details

- `subscriberEndpoint`: is this referring to Dapr or App endpoint? I created a public endpoint for testing against my local env using **ngrok** since Event Grid is expecting HTTPS for custom web hooks. My first quess was to point to Dapr but my understading is that it doesn't have something like `/api/events`. 

- `handshakePort`: what should this be exactly? I'm using default ports (Dapr - 3500, .NET Core - 5000)

Maybe the biggest question I have regarding this input binding is that will Dapr handle the `validationcode` behind the scenes or are we expected to handle that ourselves like here: https://github.com/Azure-Samples/azure-event-grid-viewer/blob/master/viewer/Controllers/UpdatesController.cs#L95.

It's a pity there's very little examples on pure .NET core apps. I found one blob post which gives some idea but that's about it: https://itnext.io/tutorial-using-azure-event-hubs-with-the-dapr-framework-81c749b66dcf

**Comment by lynn-orrell** [comment]
@Masahigo -

My apologies for any confusion! Happy to help get you up and running and would welcome any tweaks to the documentation that you see fit.

`subscriberEndpoint` refers to the public endpoint that EventGrid will talk to to send messages. In your case, it would be the public ngrok address (https).

`handshakePort` refers to the port that the EventGrid binding will listen on for incoming requests from EventGrid (ultimately an http server is spun up on this port to handle EventGrid requests). It is not the same as the port that your application may be listening on for web requests, nor the port that dapr is listening on for API requests. In my example, I choose 9000 (arbitrarily), my app listens on port 5000 and dapr listens on port 3500. For example, if you choose port 9000 as well, your ngrok command will look like this: `ngrok http -host-header=localhost 9000`

As far as the handshaking goes, the binding handles all of it so you shouldn't need to worry about it.

Hopefully this helps! If not, please ping me and I'll be happy to help where I can.

**Comment by Masahigo** [comment]
@lynn-orrell Thanks for the tips! I managed to figure this out now.

There was actually one part missing in the instructions I believe. I got this error when Dapr was trying to create the event subscription to Event Grid:

```== DAPR == time="2020-05-25T20:19:37.6636572+03:00" level=error msg="error reading from input binding eventgrid-input: eventgrid.EventSubscriptionsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Er..
rizationFailed\" Message=\"The client 'xxx' with object id 'xxx' does not have authorization to perform action 'Microsoft.EventGrid/eventSubscriptions/write'
```
So basically the Service Principal needs to have this specific permission so Dapr's input binding can create resources (event subscriptions) to Event Grid. Now I get it 👍 

I put together some Gists based on my findings:

https://gist.github.com/Masahigo/e92cfad3503066ad13865f75935ee1ec
https://gist.github.com/Masahigo/5c14f2ef0b02141c4eb37af2b2110de6
https://gist.github.com/Masahigo/41ab487579b6668a10acca002911c2e3

@lynn-orrell Great job on the input binding! I have additional feature requests: could there be support for filtering based on event types? Of course this can be done on code level as I'm doing now but could be useful.

**Comment by lynn-orrell** [comment]
@Masahigo glad you got it working! These gists are great and would be a welcome addition to the documentation (would love to see a docs PR for this... *wink* *wink*). As for the filtering, it's definitely something I've been considering but just need to work out the best way to express them declaratively in yaml since they can get fairly involved with boolean logic. Would love to hear if you have any thoughts on this...

**Comment by Masahigo** [comment]
@lynn-orrell I promise to create docs PR if you can advise on this last bit ;D

I'm now trying to deploy my service with Dapr to k8s. For the Event Grid custom webhook I need SSL/TLS for the k8s cluster. 

I followed the official instructions for deploying Dapr to k8s using Helm3: https://github.com/dapr/docs/blob/master/getting-started/environment-setup.md#install-dapr-to-kubernetes

Then I took example from NodeJS bindings example (https://github.com/dapr/samples/blob/master/5.bindings/) and managed to deploy my app to cluster as well:

**myapp.yaml**

```yml
kind: Service
apiVersion: v1
metadata:
  name: video-indexer
  labels:
    app: dotnetwebapi
spec:
  selector:
    app: dotnetwebapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-indexer
  labels:
    app: dotnetwebapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetwebapi
  template:
    metadata:
      labels:
        app: dotnetwebapi
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "video-indexer"
        dapr.io/port: "5000"
    spec:
      containers:
      - name: webapi
        image: masahigo/video-indexer:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
```

**k8s resources**

```bash
$ kubectl logs --selector=app=dotnetwebapi -c webapi
      Tap W to add a work item to the background queue.

info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://0.0.0.0:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /publish

$ kubectl logs --selector=app=dotnetwebapi -c daprd
time="2020-05-28T15:38:20.264184746Z" level=info msg="enabled monitoring middleware." app_id=video-indexer instance=video-indexer-745468cdd8-8lf5p scope=dapr.runtime.grpc.internal type=log ver=0.7.1
time="2020-05-28T15:38:20.264279046Z" level=info msg="sending workload csr request to sentry" app_id=video-indexer instance=video-indexer-745468cdd8-8lf5p scope=dapr.runtime.grpc.internal type=log ver=0.7.1
time="2020-05-28T15:38:20.31883156Z" level=info msg="certificate signed successfully" app_id=video-indexer instance=video-indexer-745468cdd8-8lf5p scope=dapr.runtime.grpc.internal type=log ver=0.7.1
time="2020-05-28T15:38:20.31898596Z" level=info msg="internal gRPC server is running on port 50002" app_id=video-indexer instance=video-indexer-745468cdd8-8lf5p scope=dapr.runtime type=log ver=0.7.1
time="2020-05-28T15:38:20.31902866Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2020-05-29 15:53:20 +0000 UTC" app_id=video-indexer instance=video-indexer-745468cdd8-8lf5p scope=dapr.runtime.grpc.internal type=log ver=0.7.1
time="2020-05-28T15:38:20.31912046Z" level=info msg="enabled cors http middleware" app_id=video-indexer instance=video-indexer-745468cdd8-8lf5p scope=dapr.runtime.http type=log ver=0.7.1
time="2020-05-28T15:38:20.31913406Z" level=info msg="enabled proxy http middleware" app_id=video-indexer instance=video-indexer-745468cdd8-8lf5p scope=dapr.runtime.http type=log ver=0.7.1
time="2020-05-28T15:38:20.31914126Z" level=info msg="enabled tracing http middleware" app_id=video-indexer instance=video-indexer-745468cdd8-8lf5p scope=dapr.runtime.http type=log ver=0.7.1
time="2020-05-28T15:38:20.31915026Z" level=info msg="http server is running on port 3500" app_id=video-indexer instance=video-indexer-745468cdd8-8lf5p scope=dapr.runtime type=log ver=0.7.1
time="2020-05-28T15:38:20.31916216Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 189.81399299999998ms" app_id=video-indexer instance=video-indexer-745468cdd8-8lf5p scope=dapr.runtime type=log ver=0.7.1

$ kubectl get all
NAME                                 READY   STATUS    RESTARTS   AGE
pod/redis-master-0                   1/1     Running   0          89m
pod/redis-slave-0                    1/1     Running   0          89m
pod/redis-slave-1                    1/1     Running   0          87m
pod/video-indexer-745468cdd8-8lf5p   2/2     Running   0          44m

NAME                         TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                               AGE
service/kubernetes           ClusterIP      10.0.0.1       <none>        443/TCP                               138m
service/redis-headless       ClusterIP      None           <none>        6379/TCP                              89m
service/redis-master         ClusterIP      10.0.39.46     <none>        6379/TCP                              89m
service/redis-slave          ClusterIP      10.0.110.212   <none>        6379/TCP                              89m
service/video-indexer        LoadBalancer   10.0.68.180    52.143.28.2   80:30587/TCP                          44m
service/video-indexer-dapr   ClusterIP      None           <none>        80/TCP,50001/TCP,50002/TCP,9090/TCP   44m

NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/video-indexer   1/1     1            1           44m

NAME                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/video-indexer-745468cdd8   1         1         1       44m

NAME                            READY   AGE
statefulset.apps/redis-master   1/1     89m
statefulset.apps/redis-slave    2/2     89m

NAME                           AGE
component.dapr.io/statestore   85m
```

So as the next step I'd need to install ingress/tls (for the Event Grid custom webhook endpoint) - been trying to accomplish that following MS docs: https://docs.microsoft.com/en-us/azure/aks/ingress-tls#create-an-ingress-controller

But the minute I deploy either Ingress controller or Cert manager to the cluster using Helm3 those go to crashloop / don't function.

I tried looking from Dapr docs and elsewhere but don't find any examples. 

_Do you have some ideas on this?_ I could create a great end-to-end example from this if I could get this last fundamental issue sorted out..

**Comment by Masahigo** [comment]
_Update: I got the Ingress/TLS working now (Azure DNS zone needed to reside in same RG with the AKS cluster)._ 

Last thing to figure out is the ingress for public HTTPS --> port 9000 in cluster.

**Comment by Masahigo** [comment]
I think I'm getting close but seems as if the Dapr sidecar for my app is not picking up the bindings being deployed to the cluster - do they need to share the same `k8s namespace`?

deploy/**dapr-sidecar-ingress.yaml**

```yml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dapr-sidecar-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
      - dapr-sidecar.dev.msdevopsdude.com
      secretName: dapr-sidecar-cert
  rules:
  - host: dapr-sidecar.dev.msdevopsdude.com
    http:
      paths:
      - backend:
          serviceName: video-indexer-dapr
          servicePort: 9000
        path: /
```
deploy/**eventgrid.yml**

```yml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eventgrid-input
spec:
  type: bindings.azure.eventgrid
  metadata:
  # Required Input Binding Metadata
  ...
  - name: subscriberEndpoint
    value: "https://dapr-sidecar.dev.msdevopsdude.com/api/events"  
  - name: handshakePort
    value: 9000
  - name: scope
    value: "..."
```
k8s commands

```bash
# deploy ingress
$ kubectl apply -f ./deploy/dapr-sidecar-ingress.yaml
..
$ kubectl get ing dapr-sidecar-ingress

NAME                   HOSTS                               ADDRESS      PORTS     AGE
dapr-sidecar-ingress   dapr-sidecar.dev.msdevopsdude.com   10.240.0.4   80, 443   10m

# deploy event grid binding
kubectl apply -f ./deploy/eventgrid.yaml

$ kubectl logs --selector=app=dotnetwebapi -c daprd
time="2020-05-28T18:39:02.057134276Z" level=info msg="enabled monitoring middleware." app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime.grpc.internal type=log ver=0.7.1
time="2020-05-28T18:39:02.057145277Z" level=info msg="sending workload csr request to sentry" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime.grpc.internal type=log ver=0.7.1
time="2020-05-28T18:39:02.098117894Z" level=info msg="certificate signed successfully" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime.grpc.internal type=log ver=0.7.1
time="2020-05-28T18:39:02.098344708Z" level=info msg="internal gRPC server is running on port 50002" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime type=log ver=0.7.1
time="2020-05-28T18:39:02.098507518Z" level=info msg="enabled cors http middleware" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime.http type=log ver=0.7.1
time="2020-05-28T18:39:02.098519919Z" level=info msg="enabled proxy http middleware" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime.http type=log ver=0.7.1
time="2020-05-28T18:39:02.09854552Z" level=info msg="enabled tracing http middleware" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime.http type=log ver=0.7.1
time="2020-05-28T18:39:02.098554821Z" level=info msg="http server is running on port 3500" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime type=log ver=0.7.1
time="2020-05-28T18:39:02.098565922Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 142.393448ms" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime type=log ver=0.7.1
time="2020-05-28T18:39:02.098660027Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2020-05-29 18:54:02 +0000 UTC" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime.grpc.internal type=log ver=0.7.1

$ kubectl get services

NAME                 TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                               AGE
kubernetes           ClusterIP      10.0.0.1       <none>         443/TCP                               77m
redis-headless       ClusterIP      None           <none>         6379/TCP                              68m
redis-master         ClusterIP      10.0.71.8      <none>         6379/TCP                              68m
redis-slave          ClusterIP      10.0.164.138   <none>         6379/TCP                              68m
video-indexer        LoadBalancer   10.0.79.10     xxx         80:32473/TCP                          18m
video-indexer-dapr   ClusterIP      None           <none>         80/TCP,50001/TCP,50002/TCP,9090/TCP   18m
```
I think there's two issue
- Dapr sidecar is not picking up the `components` I deploy to cluster
- The Nginx ingress is not configured correctly yet

**Comment by yaron2** [comment]
> I think I'm getting close but seems as if the Dapr sidecar for my app is not picking up the bindings being deployed to the cluster - do they need to share the same `k8s namespace`?
> 
> deploy/**dapr-sidecar-ingress.yaml**
> 
> ```yaml
> apiVersion: networking.k8s.io/v1beta1
> kind: Ingress
> metadata:
>   name: dapr-sidecar-ingress
>   annotations:
>     kubernetes.io/ingress.class: nginx
>     cert-manager.io/cluster-issuer: letsencrypt
> spec:
>   tls:
>     - hosts:
>       - dapr-sidecar.dev.msdevopsdude.com
>       secretName: dapr-sidecar-cert
>   rules:
>   - host: dapr-sidecar.dev.msdevopsdude.com
>     http:
>       paths:
>       - backend:
>           serviceName: video-indexer-dapr
>           servicePort: 9000
>         path: /
> ```
> 
> deploy/**eventgrid.yml**
> 
> ```yaml
> apiVersion: dapr.io/v1alpha1
> kind: Component
> metadata:
>   name: eventgrid-input
> spec:
>   type: bindings.azure.eventgrid
>   metadata:
>   # Required Input Binding Metadata
>   ...
>   - name: subscriberEndpoint
>     value: "https://dapr-sidecar.dev.msdevopsdude.com/api/events"  
>   - name: handshakePort
>     value: 9000
>   - name: scope
>     value: "..."
> ```
> 
> k8s commands
> 
> ```shell
> # deploy ingress
> $ kubectl apply -f ./deploy/dapr-sidecar-ingress.yaml
> ..
> $ kubectl get ing dapr-sidecar-ingress
> 
> NAME                   HOSTS                               ADDRESS      PORTS     AGE
> dapr-sidecar-ingress   dapr-sidecar.dev.msdevopsdude.com   10.240.0.4   80, 443   10m
> 
> # deploy event grid binding
> kubectl apply -f ./deploy/eventgrid.yaml
> 
> $ kubectl logs --selector=app=dotnetwebapi -c daprd
> time="2020-05-28T18:39:02.057134276Z" level=info msg="enabled monitoring middleware." app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime.grpc.internal type=log ver=0.7.1
> time="2020-05-28T18:39:02.057145277Z" level=info msg="sending workload csr request to sentry" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime.grpc.internal type=log ver=0.7.1
> time="2020-05-28T18:39:02.098117894Z" level=info msg="certificate signed successfully" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime.grpc.internal type=log ver=0.7.1
> time="2020-05-28T18:39:02.098344708Z" level=info msg="internal gRPC server is running on port 50002" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime type=log ver=0.7.1
> time="2020-05-28T18:39:02.098507518Z" level=info msg="enabled cors http middleware" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime.http type=log ver=0.7.1
> time="2020-05-28T18:39:02.098519919Z" level=info msg="enabled proxy http middleware" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime.http type=log ver=0.7.1
> time="2020-05-28T18:39:02.09854552Z" level=info msg="enabled tracing http middleware" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime.http type=log ver=0.7.1
> time="2020-05-28T18:39:02.098554821Z" level=info msg="http server is running on port 3500" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime type=log ver=0.7.1
> time="2020-05-28T18:39:02.098565922Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 142.393448ms" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime type=log ver=0.7.1
> time="2020-05-28T18:39:02.098660027Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2020-05-29 18:54:02 +0000 UTC" app_id=video-indexer instance=video-indexer-745468cdd8-tqm2s scope=dapr.runtime.grpc.internal type=log ver=0.7.1
> 
> $ kubectl get services
> 
> NAME                 TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                               AGE
> kubernetes           ClusterIP      10.0.0.1       <none>         443/TCP                               77m
> redis-headless       ClusterIP      None           <none>         6379/TCP                              68m
> redis-master         ClusterIP      10.0.71.8      <none>         6379/TCP                              68m
> redis-slave          ClusterIP      10.0.164.138   <none>         6379/TCP                              68m
> video-indexer        LoadBalancer   10.0.79.10     xxx         80:32473/TCP                          18m
> video-indexer-dapr   ClusterIP      None           <none>         80/TCP,50001/TCP,50002/TCP,9090/TCP   18m
> 
> $ curl -i https://dapr-sidecar.dev.msdevopsdude.com/api/events
> HTTP/2 503 
> server: nginx/1.17.10
> ```
> 
> I think there's two issue
> 
> * Dapr sidecar is not picking up the `components` I deploy to cluster
> * The Nginx ingress is not configured correctly yet

Yes they need to share the same namespace.

**Comment by Masahigo** [comment]
@yaron2 Can you be more specific?

I followed Carlos Mendible's example on "Daprizing" the Nginx ingress controller and deployed both that and certmanager to `default` namespace.

This is what my **k8s ingress** looks like now

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-rules
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - dapr.dev.msdevopsdude.com
      secretName: dapr-cert
  rules:
    - host: dapr.dev.msdevopsdude.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-ingress-dapr
              servicePort: 80
```

I also removed _LoadBalancer_ from my app since it's internal to the cluster.

Now the ingress is at least forwarding traffic

```bash
$ curl -i https://dapr.dev.msdevopsdude.com/api/event
HTTP/2 404 
```

But the Dapr sidecar for my app is still not picking up the `components` I've deployed to cluster (default namespace) so I cannot fully test this through.

**k8s services** look like this now

```bash
$ kubectl get svc
NAME                                  TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                               AGE
cert-manager                          ClusterIP      10.0.136.115   <none>          9402/TCP                              59m
cert-manager-webhook                  ClusterIP      10.0.10.64     <none>          443/TCP                               59m
kubernetes                            ClusterIP      10.0.0.1       <none>          443/TCP                               17h
nginx-ingress-dapr                    ClusterIP      None           <none>          80/TCP,50001/TCP,50002/TCP,9090/TCP   64m
nginx-nginx-ingress-controller        LoadBalancer   10.0.213.107   52.143.11.144   80:32043/TCP,443:31171/TCP            64m
nginx-nginx-ingress-default-backend   ClusterIP      10.0.177.57    <none>          80/TCP                                64m
redis-headless                        ClusterIP      None           <none>          6379/TCP                              17h
redis-master                          ClusterIP      10.0.71.8      <none>          6379/TCP                              17h
redis-slave                           ClusterIP      10.0.164.138   <none>          6379/TCP                              17h
video-indexer-dapr                    ClusterIP      None           <none>          80/TCP,50001/TCP,50002/TCP,9090/TCP   39m
```

Supporting port 9000 would probably still require some tuning to the ingress.

**Comment by Masahigo** [comment]
Okay, now Dapr sidecar seems to pick up the `components`.

Then I could see an error related to the event grid binding in Dapr sidecar's logs

```bash
$ kubectl logs video-indexer-5ffbc985f4-9s4zd -c daprd
time="2020-05-29T15:03:18.505800188Z" level=info msg="starting Dapr Runtime -- version 0.7.1 -- commit 16838e8" app_id=video-indexer instance=video-indexer-5ffbc985f4-9s4zd scope=dapr.runtime type=log ver=0.7.1
time="2020-05-29T15:03:18.50583659Z" level=info msg="log level set to: debug" app_id=video-indexer instance=video-indexer-5ffbc985f4-9s4zd scope=dapr.runtime type=log ver=0.7.1
time="2020-05-29T15:03:18.506032705Z" level=info msg="metrics server started on :9090/" app_id=video-indexer instance=video-indexer-5ffbc985f4-9s4zd scope=dapr.metrics type=log ver=0.7.1
time="2020-05-29T15:03:18.506219419Z" level=info msg="loading default configuration" app_id=video-indexer instance=video-indexer-5ffbc985f4-9s4zd scope=dapr.runtime type=log ver=0.7.1
time="2020-05-29T15:03:18.506289324Z" level=info msg="kubernetes mode configured" app_id=video-indexer instance=video-indexer-5ffbc985f4-9s4zd scope=dapr.runtime type=log ver=0.7.1
time="2020-05-29T15:03:18.506312026Z" level=info msg="app id: video-indexer" app_id=video-indexer instance=video-indexer-5ffbc985f4-9s4zd scope=dapr.runtime type=log ver=0.7.1
time="2020-05-29T15:03:18.506345628Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=video-indexer instance=video-indexer-5ffbc985f4-9s4zd scope=dapr.runtime type=log ver=0.7.1
time="2020-05-29T15:03:18.506529542Z" level=info msg="trust anchors and cert chain extracted successfully" app_id=video-indexer instance=video-indexer-5ffbc985f4-9s4zd scope=dapr.runtime.security type=log ver=0.7.1
time="2020-05-29T15:03:18.506548043Z" level=info msg="authenticator created" app_id=video-indexer instance=video-indexer-5ffbc985f4-9s4zd scope=dapr.runtime type=log ver=0.7.1
time="2020-05-29T15:03:18.551698514Z" level=warning msg="failed to load components: rpc error: code = Unknown desc = error getting components: v1alpha1.ComponentList.Items: []v1alpha1.Component: v1alpha1.Component.v1alpha1.Component.Spec: v1alpha1.ComponentSpec.Metadata: []v1alpha1.MetadataItem: v1alpha1.MetadataItem.Value: ReadString: expects \" or n, but found 9, error found in #10 byte of ...|,\"value\":9000},{\"nam|..., bigger context ...|com/api/events\"},{\"name\":\"handshakePort\",\"value\":9000},{\"name\":\"scope\",\"value\":\"/subscriptions/cff7c|..." app_id=video-indexer instance=video-indexer-5ffbc985f4-9s4zd scope=dapr.runtime type=log ver=0.7.1
```

Based on this [comment](https://github.com/kubernetes/kubernetes/issues/57509#issuecomment-353509068) _I added quotes around the handshake port_ **9000** in config (eventgrid.yml) and redeployed both the `component` and my app.

After this, based on Dapr sidecar's logs everything is working but I can see that the binding is not able to create the custom webhook to Azure Event Grid and thus my app is not getting triggered either.

@lynn-orrell Has this binding been tested in k8s?

**Comment by lynn-orrell** [comment]
Your Service and Ingress should look similar to this (notice port 80 and 9000 are defined on the service):

```yaml
kind: Service
apiVersion: v1
metadata:
  name: eventgrid-inputbindingexample
  namespace: dapr-examples
  labels:
    app: eventgrid-inputbindingexample
spec:
  selector:
    app: eventgrid-inputbindingexample
  ports:
    - name: dotnet
      protocol: TCP
      port: 80
      targetPort: 80
    - name: dapr-eventgrid
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eventgrid-inputbindingexample
  namespace: dapr-examples
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - dapr-examples.centralus.cloudapp.azure.com
      secretName: dapr-examples-tls
  rules:
    - host: dapr-examples.centralus.cloudapp.azure.com
      http:
        paths:
          - path: /api/events
            backend:
              serviceName: eventgrid-inputbindingexample
              servicePort: 9000
```

**Comment by Masahigo** [comment]
@lynn-orrell I got it working now! Thanks a million, PR coming soon ;)

**Comment by Masahigo** [comment]
@lynn-orrell I tried pushing my additions to upstream but getting 403 - I need to request access first?

https://github.com/Masahigo/docs/commit/28d4336da9a4cd6f18b7ce1ea191373fa774f19a

**Comment by lynn-orrell** [comment]
Only the maintainers can merge upstream so you'll need to open a PR. Thank you for your contribution, btw!

**Comment by Masahigo** [comment]
> Only the maintainers can merge upstream so you'll need to open a PR. Thank you for your contribution, btw!

No problem, glad to help.

Here you go: https://github.com/dapr/docs/pull/618

I encountered some issues with Nginx controller's routing with Dapr. It turned out I had to "reload" the Nginx controller's pod to sort it out.

**Pull request merged**
