### PR TITLE
Add Dapr with Docker-compose docs

### PR DESCRIPTION
**Pull request by jjcollinge**
# Description
This extends the docs to cover usage with docker inline with the following changes:
- [Docker compose sample](https://github.com/dapr/samples/pull/211)
- [Use host address for mdns register ](https://github.com/dapr/dapr/pull/1577)
- [Update mDNS resolver to respect service IP address](https://github.com/dapr/components-contrib/pull/341)

## Issue reference

Please reference the issue this PR will close: #589 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by youngbupark** [comment]
@jjcollinge Can you complete this doc ? 

Structure needs to be changed based on this template - https://github.com/dapr/docs/blob/master/contributing/README.md#contributing-to-how-tos

**Comment by jjcollinge** [comment]
@youngbupark updated - I've tried to align it with the template as best possible - the article doesn't really fit into the model of prereq, steps, cleanup - maybe that's an indication it should be split up but think that would break the context. It's still marked as WIP as it has links in it that assume that https://github.com/dapr/samples/pull/211 will be merged as is - that'll need merging first. Also I've not had time to validate that https://github.com/dapr/docs/blob/ac7a586477536b315a98a5038728cf74b417a018/howto/run-with-docker/README.md#run-dapr-in-a-docker-container-with-an-app-as-a-process works as expected on a Linux host. I can spin up a VM to test it later, will update once done.

**Comment by youngbupark** [comment]
> @youngbupark updated - I've tried to align it with the template as best possible - the article doesn't really fit into the model of prereq, steps, cleanup - maybe that's an indication it should be split up but think that would break the context. It's still marked as WIP as it has links in it that assume that [dapr/samples#211](https://github.com/dapr/samples/pull/211) will be merged as is - that'll need merging first. Also I've not had time to validate that https://github.com/dapr/docs/blob/ac7a586477536b315a98a5038728cf74b417a018/howto/run-with-docker/README.md#run-dapr-in-a-docker-container-with-an-app-as-a-process works as expected on a Linux host. I can spin up a VM to test it later, will update once done.

Thanks @jjcollinge for writing up this.

@orizohar @msfussell Please review this doc.

**Comment by orizohar** [comment]
@jjcollinge - thanks for writing this up! I pushed some minor changes (mostly removing "we" and "I" which are not part of our docs style guidelines)

Have you had a chance to complete the testing you were planning to?

**Comment by jjcollinge** [comment]
> 
> 
> @jjcollinge - thanks for writing this up! I pushed some minor changes (mostly removing "we" and "I" which are not part of our docs style guidelines)
> 
> Have you had a chance to complete the testing you were planning to?

@orizohar yes I validated this works on a Linux host as documented

**Pull request merged**
