### PR TITLE
Create setup-snssqs

### PR DESCRIPTION
**Pull request by khous**
Add documentation on how to use snssqs for local and AWS development

# Description

Add documentation for SNS/SQS usage 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

### CODE REVIEW

**Comment by yaron2** [comment]
cc @orizohar

**Comment by khous** [comment]
> Thank you for your contribution! Can you please review the following guidance on "how-to" contribution and make sure this article conforms to these guidelines in terms of style and structure? There is a reference template that can be useful for this as well.
> 
> https://github.com/dapr/docs/blob/master/contributing/README.md#contributing-to-how-tos

The structure of this article was copied directly from the article for kafka

**Comment by orizohar** [comment]
Yes, I understand, we do need to go back and improve the rest of these (they were created before we gave this guidance). For this one, if you can just add a "Related Links" section at the bottom and add a few links to other docs that would be great.

Additionally, please include in this PR a link into this doc from https://github.com/dapr/docs/blob/master/howto/setup-pub-sub-message-broker/README.md#reference

**Comment by orizohar** [comment]
Thanks for adding the links. I've made some changes that are mostly cosmetic. Also, from 0.8 per https://github.com/dapr/cli/issues/340 Dapr CLI will no longer create a components folder in working path when executing `dapr run`. Please see changes. Thanks again for your contribution!

**Pull request merged**
