### PR TITLE
adds Helm 3 support

### PR DESCRIPTION
**Pull request by nmeisenzahl**
# Description

updates all helm commands to work with Helm 3

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #265

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [x] Extended the documentation

### CODE REVIEW

**Comment by nmeisenzahl** [comment]
Hey @yaron2, good point. I will draft something later.

**Comment by nmeisenzahl** [comment]
@yaron2 Helm 2.x and 3.x are now both included.

**Comment by nmeisenzahl** [comment]
@yaron2 Do you want me to include anything further?

**Comment by youngbupark** [comment]
@nmeisenzahl I'm closing this. We migrated helm v2 to helm v3 in this milestone because new sentry requires helm v3. This change is included in https://github.com/dapr/docs/pull/307

Thanks for your contribution! :)

**Pull request closed without merging**
